-- Insert icon files into the file table
INSERT INTO file (url, mime_type, size_bytes, width, height, created_at, updated_at)
VALUES
    ('http://minio:9000/notes-app/icons/default.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/address-book.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/airplane.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/alien.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/axe.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/baby-carriage.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/baby.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/bandaids.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/bank.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/barbell.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/beach-ball.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/bomb.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/brandy.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/briefcase-metal.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/cactus.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/calendar.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/car.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/cheers.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/code.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/coins.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/currency-btc.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/database.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/dog.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/dress.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/fire.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/flask.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/game-controller.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/ghost.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/github-logo.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('http://minio:9000/notes-app/icons/student.svg', 'image/svg+xml', 1500, 24, 24, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
