// Code generated by MockGen. DO NOT EDIT.
// Source: gateway_service/internal/auth/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=gateway_service/internal/auth/repository/repository.go -destination=gateway_service/internal/auth/repository/mock/mock_client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	v1 "backend/auth_service/pkg/auth/v1"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockAuthClient is a mock of AuthClient interface.
type MockAuthClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthClientMockRecorder
	isgomock struct{}
}

// MockAuthClientMockRecorder is the mock recorder for MockAuthClient.
type MockAuthClientMockRecorder struct {
	mock *MockAuthClient
}

// NewMockAuthClient creates a new mock instance.
func NewMockAuthClient(ctrl *gomock.Controller) *MockAuthClient {
	mock := &MockAuthClient{ctrl: ctrl}
	mock.recorder = &MockAuthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthClient) EXPECT() *MockAuthClientMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockAuthClient) CreateSession(ctx context.Context, in *v1.CreateSessionRequest, opts ...grpc.CallOption) (*v1.CreateSessionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSession", varargs...)
	ret0, _ := ret[0].(*v1.CreateSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockAuthClientMockRecorder) CreateSession(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockAuthClient)(nil).CreateSession), varargs...)
}

// GetCSRFToken mocks base method.
func (m *MockAuthClient) GetCSRFToken(ctx context.Context, in *v1.GetCSRFTokenRequest, opts ...grpc.CallOption) (*v1.GetCSRFTokenResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCSRFToken", varargs...)
	ret0, _ := ret[0].(*v1.GetCSRFTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCSRFToken indicates an expected call of GetCSRFToken.
func (mr *MockAuthClientMockRecorder) GetCSRFToken(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCSRFToken", reflect.TypeOf((*MockAuthClient)(nil).GetCSRFToken), varargs...)
}

// GetUserIDBySession mocks base method.
func (m *MockAuthClient) GetUserIDBySession(ctx context.Context, in *v1.GetUserIDBySessionRequest, opts ...grpc.CallOption) (*v1.GetUserIDBySessionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserIDBySession", varargs...)
	ret0, _ := ret[0].(*v1.GetUserIDBySessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDBySession indicates an expected call of GetUserIDBySession.
func (mr *MockAuthClientMockRecorder) GetUserIDBySession(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDBySession", reflect.TypeOf((*MockAuthClient)(nil).GetUserIDBySession), varargs...)
}

// Logout mocks base method.
func (m *MockAuthClient) Logout(ctx context.Context, in *v1.LogoutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Logout", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthClientMockRecorder) Logout(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthClient)(nil).Logout), varargs...)
}
