// Code generated by MockGen. DO NOT EDIT.
// Source: delivery.go

// Package mock is a generated GoMock package.
package mock

import (
	models "backend/gateway_service/internal/file/models"
	context "context"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileUsecase is a mock of FileUsecase interface.
type MockFileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFileUsecaseMockRecorder
}

// MockFileUsecaseMockRecorder is the mock recorder for MockFileUsecase.
type MockFileUsecaseMockRecorder struct {
	mock *MockFileUsecase
}

// NewMockFileUsecase creates a new mock instance.
func NewMockFileUsecase(ctrl *gomock.Controller) *MockFileUsecase {
	mock := &MockFileUsecase{ctrl: ctrl}
	mock.recorder = &MockFileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileUsecase) EXPECT() *MockFileUsecaseMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFileUsecase) DeleteFile(ctx context.Context, fileID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileUsecaseMockRecorder) DeleteFile(ctx, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileUsecase)(nil).DeleteFile), ctx, fileID)
}

// GetFile mocks base method.
func (m *MockFileUsecase) GetFile(ctx context.Context, fileID uint64) (*models.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, fileID)
	ret0, _ := ret[0].(*models.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockFileUsecaseMockRecorder) GetFile(ctx, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockFileUsecase)(nil).GetFile), ctx, fileID)
}

// GetHeaders mocks base method.
func (m *MockFileUsecase) GetHeaders(ctx context.Context) ([]models.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeaders", ctx)
	ret0, _ := ret[0].([]models.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeaders indicates an expected call of GetHeaders.
func (mr *MockFileUsecaseMockRecorder) GetHeaders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeaders", reflect.TypeOf((*MockFileUsecase)(nil).GetHeaders), ctx)
}

// GetIcons mocks base method.
func (m *MockFileUsecase) GetIcons(ctx context.Context) ([]models.Icon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIcons", ctx)
	ret0, _ := ret[0].([]models.Icon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIcons indicates an expected call of GetIcons.
func (mr *MockFileUsecaseMockRecorder) GetIcons(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIcons", reflect.TypeOf((*MockFileUsecase)(nil).GetIcons), ctx)
}

// UploadFile mocks base method.
func (m *MockFileUsecase) UploadFile(ctx context.Context, file io.Reader, filename, contentType string, size int64) (*models.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, file, filename, contentType, size)
	ret0, _ := ret[0].(*models.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFileUsecaseMockRecorder) UploadFile(ctx, file, filename, contentType, size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFileUsecase)(nil).UploadFile), ctx, file, filename, contentType, size)
}
