// Code generated by MockGen. DO NOT EDIT.
// Source: blocks/delivery/delivery.go
//
// Generated by this command:
//
//	mockgen -source=blocks/delivery/delivery.go -destination=blocks/mock/mock_delivery.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	models "backend/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBlocksUsecase is a mock of BlocksUsecase interface.
type MockBlocksUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockBlocksUsecaseMockRecorder
	isgomock struct{}
}

// MockBlocksUsecaseMockRecorder is the mock recorder for MockBlocksUsecase.
type MockBlocksUsecaseMockRecorder struct {
	mock *MockBlocksUsecase
}

// NewMockBlocksUsecase creates a new mock instance.
func NewMockBlocksUsecase(ctrl *gomock.Controller) *MockBlocksUsecase {
	mock := &MockBlocksUsecase{ctrl: ctrl}
	mock.recorder = &MockBlocksUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlocksUsecase) EXPECT() *MockBlocksUsecaseMockRecorder {
	return m.recorder
}

// CreateBlock mocks base method.
func (m *MockBlocksUsecase) CreateBlock(ctx context.Context, userID, noteID uint64, afterBlockID *uint64) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlock", ctx, userID, noteID, afterBlockID)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlock indicates an expected call of CreateBlock.
func (mr *MockBlocksUsecaseMockRecorder) CreateBlock(ctx, userID, noteID, afterBlockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).CreateBlock), ctx, userID, noteID, afterBlockID)
}

// DeleteBlock mocks base method.
func (m *MockBlocksUsecase) DeleteBlock(ctx context.Context, userID, blockID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlock", ctx, userID, blockID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockBlocksUsecaseMockRecorder) DeleteBlock(ctx, userID, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).DeleteBlock), ctx, userID, blockID)
}

// GetBlock mocks base method.
func (m *MockBlocksUsecase) GetBlock(ctx context.Context, userID, blockID uint64) (*models.BlockWithContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", ctx, userID, blockID)
	ret0, _ := ret[0].(*models.BlockWithContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockBlocksUsecaseMockRecorder) GetBlock(ctx, userID, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).GetBlock), ctx, userID, blockID)
}

// GetBlocks mocks base method.
func (m *MockBlocksUsecase) GetBlocks(ctx context.Context, userID, noteID uint64) ([]models.BlockWithContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocks", ctx, userID, noteID)
	ret0, _ := ret[0].([]models.BlockWithContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocks indicates an expected call of GetBlocks.
func (mr *MockBlocksUsecaseMockRecorder) GetBlocks(ctx, userID, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocks", reflect.TypeOf((*MockBlocksUsecase)(nil).GetBlocks), ctx, userID, noteID)
}

// UpdateBlock mocks base method.
func (m *MockBlocksUsecase) UpdateBlock(ctx context.Context, userID, blockID uint64, text string, formats []models.BlockTextFormat) (*models.BlockWithContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlock", ctx, userID, blockID, text, formats)
	ret0, _ := ret[0].(*models.BlockWithContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlock indicates an expected call of UpdateBlock.
func (mr *MockBlocksUsecaseMockRecorder) UpdateBlock(ctx, userID, blockID, text, formats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).UpdateBlock), ctx, userID, blockID, text, formats)
}

// UpdateBlockPosition mocks base method.
func (m *MockBlocksUsecase) UpdateBlockPosition(ctx context.Context, userID, blockID uint64, afterBlockID *uint64) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockPosition", ctx, userID, blockID, afterBlockID)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockPosition indicates an expected call of UpdateBlockPosition.
func (mr *MockBlocksUsecaseMockRecorder) UpdateBlockPosition(ctx, userID, blockID, afterBlockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockPosition", reflect.TypeOf((*MockBlocksUsecase)(nil).UpdateBlockPosition), ctx, userID, blockID, afterBlockID)
}
