// Code generated by MockGen. DO NOT EDIT.
// Source: blocks/usecase/usecase.go
//
// Generated by this command:
//
//	mockgen -source=blocks/usecase/usecase.go -destination=blocks/mock/mock_usecase.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	"backend/models"
	"context"
	"reflect"

	"go.uber.org/mock/gomock"
)

// MockBlocksRepository is a mock of BlocksRepository interface.
type MockBlocksRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlocksRepositoryMockRecorder
}

// MockBlocksRepositoryMockRecorder is the mock recorder for MockBlocksRepository.
type MockBlocksRepositoryMockRecorder struct {
	mock *MockBlocksRepository
}

// NewMockBlocksRepository creates a new mock instance.
func NewMockBlocksRepository(ctrl *gomock.Controller) *MockBlocksRepository {
	mock := &MockBlocksRepository{ctrl: ctrl}
	mock.recorder = &MockBlocksRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlocksRepository) EXPECT() *MockBlocksRepositoryMockRecorder {
	return m.recorder
}

// CreateBlock mocks base method.
func (m *MockBlocksRepository) CreateBlock(ctx context.Context, noteID uint64, blockType models.BlockType, position float64) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBlock", ctx, noteID, blockType, position)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBlock indicates an expected call of CreateBlock.
func (mr *MockBlocksRepositoryMockRecorder) CreateBlock(ctx, noteID, blockType, position interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBlock", reflect.TypeOf((*MockBlocksRepository)(nil).CreateBlock), ctx, noteID, blockType, position)
}

// GetBlocksByNoteID mocks base method.
func (m *MockBlocksRepository) GetBlocksByNoteID(ctx context.Context, noteID uint64) ([]models.BlockWithContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksByNoteID", ctx, noteID)
	ret0, _ := ret[0].([]models.BlockWithContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksByNoteID indicates an expected call of GetBlocksByNoteID.
func (mr *MockBlocksRepositoryMockRecorder) GetBlocksByNoteID(ctx, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksByNoteID", reflect.TypeOf((*MockBlocksRepository)(nil).GetBlocksByNoteID), ctx, noteID)
}

// GetBlockByID mocks base method.
func (m *MockBlocksRepository) GetBlockByID(ctx context.Context, blockID uint64) (*models.BlockWithContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByID", ctx, blockID)
	ret0, _ := ret[0].(*models.BlockWithContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByID indicates an expected call of GetBlockByID.
func (mr *MockBlocksRepositoryMockRecorder) GetBlockByID(ctx, blockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByID", reflect.TypeOf((*MockBlocksRepository)(nil).GetBlockByID), ctx, blockID)
}

// UpdateBlockText mocks base method.
func (m *MockBlocksRepository) UpdateBlockText(ctx context.Context, blockID uint64, text string, formats []models.BlockTextFormat) (*models.BlockWithContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockText", ctx, blockID, text, formats)
	ret0, _ := ret[0].(*models.BlockWithContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockText indicates an expected call of UpdateBlockText.
func (mr *MockBlocksRepositoryMockRecorder) UpdateBlockText(ctx, blockID, text, formats interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockText", reflect.TypeOf((*MockBlocksRepository)(nil).UpdateBlockText), ctx, blockID, text, formats)
}

// UpdateBlockPosition mocks base method.
func (m *MockBlocksRepository) UpdateBlockPosition(ctx context.Context, blockID uint64, position float64) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockPosition", ctx, blockID, position)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockPosition indicates an expected call of UpdateBlockPosition.
func (mr *MockBlocksRepositoryMockRecorder) UpdateBlockPosition(ctx, blockID, position interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockPosition", reflect.TypeOf((*MockBlocksRepository)(nil).UpdateBlockPosition), ctx, blockID, position)
}

// DeleteBlock mocks base method.
func (m *MockBlocksRepository) DeleteBlock(ctx context.Context, blockID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlock", ctx, blockID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockBlocksRepositoryMockRecorder) DeleteBlock(ctx, blockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockBlocksRepository)(nil).DeleteBlock), ctx, blockID)
}

// GetBlockNoteID mocks base method.
func (m *MockBlocksRepository) GetBlockNoteID(ctx context.Context, blockID uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockNoteID", ctx, blockID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockNoteID indicates an expected call of GetBlockNoteID.
func (mr *MockBlocksRepositoryMockRecorder) GetBlockNoteID(ctx, blockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockNoteID", reflect.TypeOf((*MockBlocksRepository)(nil).GetBlockNoteID), ctx, blockID)
}

// BlockPositionInfo is a helper type for GetBlocksByNoteIDForPositionCalc
type BlockPositionInfo struct {
	ID       uint64
	Position float64
}

// GetBlocksByNoteIDForPositionCalc mocks base method.
func (m *MockBlocksRepository) GetBlocksByNoteIDForPositionCalc(ctx context.Context, noteID uint64, excludeBlockID uint64) ([]struct {
	ID       uint64
	Position float64
}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocksByNoteIDForPositionCalc", ctx, noteID, excludeBlockID)
	ret0, _ := ret[0].([]struct {
		ID       uint64
		Position float64
	})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocksByNoteIDForPositionCalc indicates an expected call of GetBlocksByNoteIDForPositionCalc.
func (mr *MockBlocksRepositoryMockRecorder) GetBlocksByNoteIDForPositionCalc(ctx, noteID, excludeBlockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocksByNoteIDForPositionCalc", reflect.TypeOf((*MockBlocksRepository)(nil).GetBlocksByNoteIDForPositionCalc), ctx, noteID, excludeBlockID)
}

// MockNotesRepository is a mock of NotesRepository interface.
type MockNotesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotesRepositoryMockRecorder
}

// MockNotesRepositoryMockRecorder is the mock recorder for MockNotesRepository.
type MockNotesRepositoryMockRecorder struct {
	mock *MockNotesRepository
}

// NewMockNotesRepository creates a new mock instance.
func NewMockNotesRepository(ctrl *gomock.Controller) *MockNotesRepository {
	mock := &MockNotesRepository{ctrl: ctrl}
	mock.recorder = &MockNotesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotesRepository) EXPECT() *MockNotesRepositoryMockRecorder {
	return m.recorder
}

// GetNoteById mocks base method.
func (m *MockNotesRepository) GetNoteById(ctx context.Context, noteID uint64) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteById", ctx, noteID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteById indicates an expected call of GetNoteById.
func (mr *MockNotesRepositoryMockRecorder) GetNoteById(ctx, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteById", reflect.TypeOf((*MockNotesRepository)(nil).GetNoteById), ctx, noteID)
}

