FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o /app/bin/gateway ./gateway_service/cmd/main.go

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/bin/gateway .
COPY --from=builder /app/config/ ./config/
COPY --from=builder /app/gateway_service/db/migrations ./db/migrations

EXPOSE 8080
CMD ["./gateway"]