
FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY pkg ./pkg
COPY auth_service ./auth_service

RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    CGO_ENABLED=0 go build -o /app/bin/auth-service ./auth_service/cmd/main.go

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/bin/auth-service .
COPY config ./config/

EXPOSE 50051
CMD ["./auth-service"]