FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY backend/go.mod backend/go.sum ./
RUN go mod download
COPY backend/ .
COPY config/ ./config/
RUN CGO_ENABLED=0 go build -o /app/auth-service ./cmd/auth/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/auth-service .
COPY --from=builder /app/config/ ./config/
EXPOSE 50051
CMD ["./auth-service"]