FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
COPY config/ ./config/

RUN CGO_ENABLED=0 go build -o /app/note-service ./cmd/notes/main.go

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/note-service .
COPY --from=builder /app/config/ ./config/

EXPOSE 50053
CMD ["./note-service"]