FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o /app/bin/auth-service ./auth_service/cmd/main.go

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/bin/auth-service .
COPY --from=builder /app/config/ ./config/

EXPOSE 50051
CMD ["./auth-service"]