// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package mock is a generated GoMock package.
package mock

import (
	models "backend/notes_service/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNoteUsecase is a mock of NoteUsecase interface.
type MockNoteUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockNoteUsecaseMockRecorder
}

// MockNoteUsecaseMockRecorder is the mock recorder for MockNoteUsecase.
type MockNoteUsecaseMockRecorder struct {
	mock *MockNoteUsecase
}

// NewMockNoteUsecase creates a new mock instance.
func NewMockNoteUsecase(ctrl *gomock.Controller) *MockNoteUsecase {
	mock := &MockNoteUsecase{ctrl: ctrl}
	mock.recorder = &MockNoteUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteUsecase) EXPECT() *MockNoteUsecaseMockRecorder {
	return m.recorder
}

// AddFavorite mocks base method.
func (m *MockNoteUsecase) AddFavorite(ctx context.Context, userID, noteID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFavorite", ctx, userID, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFavorite indicates an expected call of AddFavorite.
func (mr *MockNoteUsecaseMockRecorder) AddFavorite(ctx, userID, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFavorite", reflect.TypeOf((*MockNoteUsecase)(nil).AddFavorite), ctx, userID, noteID)
}

// CreateNote mocks base method.
func (m *MockNoteUsecase) CreateNote(ctx context.Context, userID uint64, parentNoteID *uint64) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, userID, parentNoteID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNoteUsecaseMockRecorder) CreateNote(ctx, userID, parentNoteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNoteUsecase)(nil).CreateNote), ctx, userID, parentNoteID)
}

// DeleteNote mocks base method.
func (m *MockNoteUsecase) DeleteNote(ctx context.Context, userID, noteID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, userID, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockNoteUsecaseMockRecorder) DeleteNote(ctx, userID, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockNoteUsecase)(nil).DeleteNote), ctx, userID, noteID)
}

// GetAllNotes mocks base method.
func (m *MockNoteUsecase) GetAllNotes(ctx context.Context, userID uint64) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotes", ctx, userID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotes indicates an expected call of GetAllNotes.
func (mr *MockNoteUsecaseMockRecorder) GetAllNotes(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotes", reflect.TypeOf((*MockNoteUsecase)(nil).GetAllNotes), ctx, userID)
}

// GetNoteById mocks base method.
func (m *MockNoteUsecase) GetNoteById(ctx context.Context, userID, noteID uint64) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteById", ctx, userID, noteID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteById indicates an expected call of GetNoteById.
func (mr *MockNoteUsecaseMockRecorder) GetNoteById(ctx, userID, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteById", reflect.TypeOf((*MockNoteUsecase)(nil).GetNoteById), ctx, userID, noteID)
}

// GetNoteByShareUUID mocks base method.
func (m *MockNoteUsecase) GetNoteByShareUUID(ctx context.Context, shareUUID string) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteByShareUUID", ctx, shareUUID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteByShareUUID indicates an expected call of GetNoteByShareUUID.
func (mr *MockNoteUsecaseMockRecorder) GetNoteByShareUUID(ctx, shareUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteByShareUUID", reflect.TypeOf((*MockNoteUsecase)(nil).GetNoteByShareUUID), ctx, shareUUID)
}

// RemoveFavorite mocks base method.
func (m *MockNoteUsecase) RemoveFavorite(ctx context.Context, userID, noteID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFavorite", ctx, userID, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFavorite indicates an expected call of RemoveFavorite.
func (mr *MockNoteUsecaseMockRecorder) RemoveFavorite(ctx, userID, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFavorite", reflect.TypeOf((*MockNoteUsecase)(nil).RemoveFavorite), ctx, userID, noteID)
}

// SearchNotes mocks base method.
func (m *MockNoteUsecase) SearchNotes(ctx context.Context, userID uint64, query string) (*models.SearchNotesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchNotes", ctx, userID, query)
	ret0, _ := ret[0].(*models.SearchNotesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchNotes indicates an expected call of SearchNotes.
func (mr *MockNoteUsecaseMockRecorder) SearchNotes(ctx, userID, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchNotes", reflect.TypeOf((*MockNoteUsecase)(nil).SearchNotes), ctx, userID, query)
}

// SetHeader mocks base method.
func (m *MockNoteUsecase) SetHeader(ctx context.Context, userID, noteID, headerFileID uint64) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", ctx, userID, noteID, headerFileID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockNoteUsecaseMockRecorder) SetHeader(ctx, userID, noteID, headerFileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockNoteUsecase)(nil).SetHeader), ctx, userID, noteID, headerFileID)
}

// SetIcon mocks base method.
func (m *MockNoteUsecase) SetIcon(ctx context.Context, userID, noteID, iconFileID uint64) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIcon", ctx, userID, noteID, iconFileID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetIcon indicates an expected call of SetIcon.
func (mr *MockNoteUsecaseMockRecorder) SetIcon(ctx, userID, noteID, iconFileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIcon", reflect.TypeOf((*MockNoteUsecase)(nil).SetIcon), ctx, userID, noteID, iconFileID)
}

// UpdateNote mocks base method.
func (m *MockNoteUsecase) UpdateNote(ctx context.Context, userID, noteID uint64, title *string, isArchived *bool) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, userID, noteID, title, isArchived)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockNoteUsecaseMockRecorder) UpdateNote(ctx, userID, noteID, title, isArchived interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockNoteUsecase)(nil).UpdateNote), ctx, userID, noteID, title, isArchived)
}

// MockBlocksUsecase is a mock of BlocksUsecase interface.
type MockBlocksUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockBlocksUsecaseMockRecorder
}

// MockBlocksUsecaseMockRecorder is the mock recorder for MockBlocksUsecase.
type MockBlocksUsecaseMockRecorder struct {
	mock *MockBlocksUsecase
}

// NewMockBlocksUsecase creates a new mock instance.
func NewMockBlocksUsecase(ctrl *gomock.Controller) *MockBlocksUsecase {
	mock := &MockBlocksUsecase{ctrl: ctrl}
	mock.recorder = &MockBlocksUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlocksUsecase) EXPECT() *MockBlocksUsecaseMockRecorder {
	return m.recorder
}

// CreateAttachmentBlock mocks base method.
func (m *MockBlocksUsecase) CreateAttachmentBlock(ctx context.Context, userID, noteID uint64, beforeBlockID *uint64, fileID uint64) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttachmentBlock", ctx, userID, noteID, beforeBlockID, fileID)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttachmentBlock indicates an expected call of CreateAttachmentBlock.
func (mr *MockBlocksUsecaseMockRecorder) CreateAttachmentBlock(ctx, userID, noteID, beforeBlockID, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttachmentBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).CreateAttachmentBlock), ctx, userID, noteID, beforeBlockID, fileID)
}

// CreateCodeBlock mocks base method.
func (m *MockBlocksUsecase) CreateCodeBlock(ctx context.Context, userID, noteID uint64, beforeBlockID *uint64) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCodeBlock", ctx, userID, noteID, beforeBlockID)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCodeBlock indicates an expected call of CreateCodeBlock.
func (mr *MockBlocksUsecaseMockRecorder) CreateCodeBlock(ctx, userID, noteID, beforeBlockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCodeBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).CreateCodeBlock), ctx, userID, noteID, beforeBlockID)
}

// CreateTextBlock mocks base method.
func (m *MockBlocksUsecase) CreateTextBlock(ctx context.Context, userID, noteID uint64, beforeBlockID *uint64) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTextBlock", ctx, userID, noteID, beforeBlockID)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTextBlock indicates an expected call of CreateTextBlock.
func (mr *MockBlocksUsecaseMockRecorder) CreateTextBlock(ctx, userID, noteID, beforeBlockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTextBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).CreateTextBlock), ctx, userID, noteID, beforeBlockID)
}

// DeleteBlock mocks base method.
func (m *MockBlocksUsecase) DeleteBlock(ctx context.Context, userID, blockID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlock", ctx, userID, blockID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockBlocksUsecaseMockRecorder) DeleteBlock(ctx, userID, blockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).DeleteBlock), ctx, userID, blockID)
}

// GetBlock mocks base method.
func (m *MockBlocksUsecase) GetBlock(ctx context.Context, userID, blockID uint64) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", ctx, userID, blockID)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockBlocksUsecaseMockRecorder) GetBlock(ctx, userID, blockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).GetBlock), ctx, userID, blockID)
}

// GetBlocks mocks base method.
func (m *MockBlocksUsecase) GetBlocks(ctx context.Context, userID, noteID uint64) ([]models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocks", ctx, userID, noteID)
	ret0, _ := ret[0].([]models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocks indicates an expected call of GetBlocks.
func (mr *MockBlocksUsecaseMockRecorder) GetBlocks(ctx, userID, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocks", reflect.TypeOf((*MockBlocksUsecase)(nil).GetBlocks), ctx, userID, noteID)
}

// UpdateBlock mocks base method.
func (m *MockBlocksUsecase) UpdateBlock(ctx context.Context, userID uint64, req *models.UpdateBlockRequest) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlock", ctx, userID, req)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlock indicates an expected call of UpdateBlock.
func (mr *MockBlocksUsecaseMockRecorder) UpdateBlock(ctx, userID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).UpdateBlock), ctx, userID, req)
}

// UpdateBlockPosition mocks base method.
func (m *MockBlocksUsecase) UpdateBlockPosition(ctx context.Context, userID, blockID uint64, beforeBlockID *uint64) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockPosition", ctx, userID, blockID, beforeBlockID)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockPosition indicates an expected call of UpdateBlockPosition.
func (mr *MockBlocksUsecaseMockRecorder) UpdateBlockPosition(ctx, userID, blockID, beforeBlockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockPosition", reflect.TypeOf((*MockBlocksUsecase)(nil).UpdateBlockPosition), ctx, userID, blockID, beforeBlockID)
}

// MockSharingUsecase is a mock of SharingUsecase interface.
type MockSharingUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSharingUsecaseMockRecorder
}

// MockSharingUsecaseMockRecorder is the mock recorder for MockSharingUsecase.
type MockSharingUsecaseMockRecorder struct {
	mock *MockSharingUsecase
}

// NewMockSharingUsecase creates a new mock instance.
func NewMockSharingUsecase(ctrl *gomock.Controller) *MockSharingUsecase {
	mock := &MockSharingUsecase{ctrl: ctrl}
	mock.recorder = &MockSharingUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSharingUsecase) EXPECT() *MockSharingUsecaseMockRecorder {
	return m.recorder
}

// ActivateAccessByLink mocks base method.
func (m *MockSharingUsecase) ActivateAccessByLink(ctx context.Context, shareUUID string, userID uint64) (*models.ActivateAccessResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateAccessByLink", ctx, shareUUID, userID)
	ret0, _ := ret[0].(*models.ActivateAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActivateAccessByLink indicates an expected call of ActivateAccessByLink.
func (mr *MockSharingUsecaseMockRecorder) ActivateAccessByLink(ctx, shareUUID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateAccessByLink", reflect.TypeOf((*MockSharingUsecase)(nil).ActivateAccessByLink), ctx, shareUUID, userID)
}

// AddCollaborator mocks base method.
func (m *MockSharingUsecase) AddCollaborator(ctx context.Context, noteID, currentUserID, targetUserID uint64, role models.NoteRole) (*models.NotePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCollaborator", ctx, noteID, currentUserID, targetUserID, role)
	ret0, _ := ret[0].(*models.NotePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCollaborator indicates an expected call of AddCollaborator.
func (mr *MockSharingUsecaseMockRecorder) AddCollaborator(ctx, noteID, currentUserID, targetUserID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCollaborator", reflect.TypeOf((*MockSharingUsecase)(nil).AddCollaborator), ctx, noteID, currentUserID, targetUserID, role)
}

// CheckNoteAccess mocks base method.
func (m *MockSharingUsecase) CheckNoteAccess(ctx context.Context, noteID, userID uint64) (*models.NoteAccessInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckNoteAccess", ctx, noteID, userID)
	ret0, _ := ret[0].(*models.NoteAccessInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckNoteAccess indicates an expected call of CheckNoteAccess.
func (mr *MockSharingUsecaseMockRecorder) CheckNoteAccess(ctx, noteID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNoteAccess", reflect.TypeOf((*MockSharingUsecase)(nil).CheckNoteAccess), ctx, noteID, userID)
}

// GetCollaborators mocks base method.
func (m *MockSharingUsecase) GetCollaborators(ctx context.Context, noteID, currentUserID uint64) (uint64, []*models.NotePermission, *models.NoteRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCollaborators", ctx, noteID, currentUserID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].([]*models.NotePermission)
	ret2, _ := ret[2].(*models.NoteRole)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetCollaborators indicates an expected call of GetCollaborators.
func (mr *MockSharingUsecaseMockRecorder) GetCollaborators(ctx, noteID, currentUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollaborators", reflect.TypeOf((*MockSharingUsecase)(nil).GetCollaborators), ctx, noteID, currentUserID)
}

// GetPublicAccess mocks base method.
func (m *MockSharingUsecase) GetPublicAccess(ctx context.Context, noteID, currentUserID uint64) (*models.NoteRole, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicAccess", ctx, noteID, currentUserID)
	ret0, _ := ret[0].(*models.NoteRole)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicAccess indicates an expected call of GetPublicAccess.
func (mr *MockSharingUsecaseMockRecorder) GetPublicAccess(ctx, noteID, currentUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicAccess", reflect.TypeOf((*MockSharingUsecase)(nil).GetPublicAccess), ctx, noteID, currentUserID)
}

// GetSharingSettings mocks base method.
func (m *MockSharingUsecase) GetSharingSettings(ctx context.Context, noteID, currentUserID uint64) (*models.SharingSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharingSettings", ctx, noteID, currentUserID)
	ret0, _ := ret[0].(*models.SharingSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSharingSettings indicates an expected call of GetSharingSettings.
func (mr *MockSharingUsecaseMockRecorder) GetSharingSettings(ctx, noteID, currentUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharingSettings", reflect.TypeOf((*MockSharingUsecase)(nil).GetSharingSettings), ctx, noteID, currentUserID)
}

// RemoveCollaborator mocks base method.
func (m *MockSharingUsecase) RemoveCollaborator(ctx context.Context, noteID, currentUserID, permissionID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCollaborator", ctx, noteID, currentUserID, permissionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCollaborator indicates an expected call of RemoveCollaborator.
func (mr *MockSharingUsecaseMockRecorder) RemoveCollaborator(ctx, noteID, currentUserID, permissionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCollaborator", reflect.TypeOf((*MockSharingUsecase)(nil).RemoveCollaborator), ctx, noteID, currentUserID, permissionID)
}

// SetPublicAccess mocks base method.
func (m *MockSharingUsecase) SetPublicAccess(ctx context.Context, noteID, currentUserID uint64, accessLevel *models.NoteRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPublicAccess", ctx, noteID, currentUserID, accessLevel)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPublicAccess indicates an expected call of SetPublicAccess.
func (mr *MockSharingUsecaseMockRecorder) SetPublicAccess(ctx, noteID, currentUserID, accessLevel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPublicAccess", reflect.TypeOf((*MockSharingUsecase)(nil).SetPublicAccess), ctx, noteID, currentUserID, accessLevel)
}

// UpdateCollaboratorRole mocks base method.
func (m *MockSharingUsecase) UpdateCollaboratorRole(ctx context.Context, noteID, currentUserID, permissionID uint64, newRole models.NoteRole) (*models.NotePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCollaboratorRole", ctx, noteID, currentUserID, permissionID, newRole)
	ret0, _ := ret[0].(*models.NotePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCollaboratorRole indicates an expected call of UpdateCollaboratorRole.
func (mr *MockSharingUsecaseMockRecorder) UpdateCollaboratorRole(ctx, noteID, currentUserID, permissionID, newRole interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCollaboratorRole", reflect.TypeOf((*MockSharingUsecase)(nil).UpdateCollaboratorRole), ctx, noteID, currentUserID, permissionID, newRole)
}
