// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/note/v1/note.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Note struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       uint64                 `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ParentNoteId  *uint64                `protobuf:"varint,3,opt,name=parent_note_id,json=parentNoteId,proto3,oneof" json:"parent_note_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	IconFileId    *uint64                `protobuf:"varint,5,opt,name=icon_file_id,json=iconFileId,proto3,oneof" json:"icon_file_id,omitempty"`
	IsFavorite    bool                   `protobuf:"varint,6,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	IsArchived    bool                   `protobuf:"varint,7,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	IsShared      bool                   `protobuf:"varint,8,opt,name=is_shared,json=isShared,proto3" json:"is_shared,omitempty"`
	ShareUuid     *string                `protobuf:"bytes,9,opt,name=share_uuid,json=shareUuid,proto3,oneof" json:"share_uuid,omitempty"` // НОВЫЙ - UUID для публичной ссылки
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Note) Reset() {
	*x = Note{}
	mi := &file_proto_note_v1_note_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Note) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Note) ProtoMessage() {}

func (x *Note) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_v1_note_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Note.ProtoReflect.Descriptor instead.
func (*Note) Descriptor() ([]byte, []int) {
	return file_proto_note_v1_note_proto_rawDescGZIP(), []int{0}
}

func (x *Note) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Note) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Note) GetParentNoteId() uint64 {
	if x != nil && x.ParentNoteId != nil {
		return *x.ParentNoteId
	}
	return 0
}

func (x *Note) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Note) GetIconFileId() uint64 {
	if x != nil && x.IconFileId != nil {
		return *x.IconFileId
	}
	return 0
}

func (x *Note) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *Note) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *Note) GetIsShared() bool {
	if x != nil {
		return x.IsShared
	}
	return false
}

func (x *Note) GetShareUuid() string {
	if x != nil && x.ShareUuid != nil {
		return *x.ShareUuid
	}
	return ""
}

func (x *Note) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Note) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Note) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type GetAllNotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllNotesRequest) Reset() {
	*x = GetAllNotesRequest{}
	mi := &file_proto_note_v1_note_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNotesRequest) ProtoMessage() {}

func (x *GetAllNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_v1_note_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNotesRequest.ProtoReflect.Descriptor instead.
func (*GetAllNotesRequest) Descriptor() ([]byte, []int) {
	return file_proto_note_v1_note_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllNotesRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetAllNotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notes         []*Note                `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllNotesResponse) Reset() {
	*x = GetAllNotesResponse{}
	mi := &file_proto_note_v1_note_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllNotesResponse) ProtoMessage() {}

func (x *GetAllNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_v1_note_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllNotesResponse.ProtoReflect.Descriptor instead.
func (*GetAllNotesResponse) Descriptor() ([]byte, []int) {
	return file_proto_note_v1_note_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllNotesResponse) GetNotes() []*Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

type CreateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ParentNoteId  *uint64                `protobuf:"varint,2,opt,name=parent_note_id,json=parentNoteId,proto3,oneof" json:"parent_note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteRequest) Reset() {
	*x = CreateNoteRequest{}
	mi := &file_proto_note_v1_note_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRequest) ProtoMessage() {}

func (x *CreateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_v1_note_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_note_v1_note_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNoteRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateNoteRequest) GetParentNoteId() uint64 {
	if x != nil && x.ParentNoteId != nil {
		return *x.ParentNoteId
	}
	return 0
}

type GetNoteByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteByIdRequest) Reset() {
	*x = GetNoteByIdRequest{}
	mi := &file_proto_note_v1_note_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteByIdRequest) ProtoMessage() {}

func (x *GetNoteByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_v1_note_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteByIdRequest.ProtoReflect.Descriptor instead.
func (*GetNoteByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_note_v1_note_proto_rawDescGZIP(), []int{4}
}

func (x *GetNoteByIdRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetNoteByIdRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type GetNoteByShareUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareUuid     string                 `protobuf:"bytes,1,opt,name=share_uuid,json=shareUuid,proto3" json:"share_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNoteByShareUUIDRequest) Reset() {
	*x = GetNoteByShareUUIDRequest{}
	mi := &file_proto_note_v1_note_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNoteByShareUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNoteByShareUUIDRequest) ProtoMessage() {}

func (x *GetNoteByShareUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_v1_note_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNoteByShareUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetNoteByShareUUIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_note_v1_note_proto_rawDescGZIP(), []int{5}
}

func (x *GetNoteByShareUUIDRequest) GetShareUuid() string {
	if x != nil {
		return x.ShareUuid
	}
	return ""
}

type UpdateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	IsArchived    *bool                  `protobuf:"varint,4,opt,name=is_archived,json=isArchived,proto3,oneof" json:"is_archived,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteRequest) Reset() {
	*x = UpdateNoteRequest{}
	mi := &file_proto_note_v1_note_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteRequest) ProtoMessage() {}

func (x *UpdateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_v1_note_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_note_v1_note_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateNoteRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateNoteRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *UpdateNoteRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateNoteRequest) GetIsArchived() bool {
	if x != nil && x.IsArchived != nil {
		return *x.IsArchived
	}
	return false
}

type DeleteNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNoteRequest) Reset() {
	*x = DeleteNoteRequest{}
	mi := &file_proto_note_v1_note_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNoteRequest) ProtoMessage() {}

func (x *DeleteNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_v1_note_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_note_v1_note_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteNoteRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteNoteRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type FavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteRequest) Reset() {
	*x = FavoriteRequest{}
	mi := &file_proto_note_v1_note_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteRequest) ProtoMessage() {}

func (x *FavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_note_v1_note_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteRequest.ProtoReflect.Descriptor instead.
func (*FavoriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_note_v1_note_proto_rawDescGZIP(), []int{8}
}

func (x *FavoriteRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FavoriteRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

var File_proto_note_v1_note_proto protoreflect.FileDescriptor

const file_proto_note_v1_note_proto_rawDesc = "" +
	"\n" +
	"\x18proto/note/v1/note.proto\x12\x04note\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x94\x04\n" +
	"\x04Note\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x04R\aownerId\x12)\n" +
	"\x0eparent_note_id\x18\x03 \x01(\x04H\x00R\fparentNoteId\x88\x01\x01\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12%\n" +
	"\ficon_file_id\x18\x05 \x01(\x04H\x01R\n" +
	"iconFileId\x88\x01\x01\x12\x1f\n" +
	"\vis_favorite\x18\x06 \x01(\bR\n" +
	"isFavorite\x12\x1f\n" +
	"\vis_archived\x18\a \x01(\bR\n" +
	"isArchived\x12\x1b\n" +
	"\tis_shared\x18\b \x01(\bR\bisShared\x12\"\n" +
	"\n" +
	"share_uuid\x18\t \x01(\tH\x02R\tshareUuid\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\x03R\tdeletedAt\x88\x01\x01B\x11\n" +
	"\x0f_parent_note_idB\x0f\n" +
	"\r_icon_file_idB\r\n" +
	"\v_share_uuidB\r\n" +
	"\v_deleted_at\"-\n" +
	"\x12GetAllNotesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"7\n" +
	"\x13GetAllNotesResponse\x12 \n" +
	"\x05notes\x18\x01 \x03(\v2\n" +
	".note.NoteR\x05notes\"j\n" +
	"\x11CreateNoteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12)\n" +
	"\x0eparent_note_id\x18\x02 \x01(\x04H\x00R\fparentNoteId\x88\x01\x01B\x11\n" +
	"\x0f_parent_note_id\"F\n" +
	"\x12GetNoteByIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\":\n" +
	"\x19GetNoteByShareUUIDRequest\x12\x1d\n" +
	"\n" +
	"share_uuid\x18\x01 \x01(\tR\tshareUuid\"\xa0\x01\n" +
	"\x11UpdateNoteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12$\n" +
	"\vis_archived\x18\x04 \x01(\bH\x01R\n" +
	"isArchived\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_is_archived\"E\n" +
	"\x11DeleteNoteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\"C\n" +
	"\x0fFavoriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId2\xed\x03\n" +
	"\vNoteService\x12B\n" +
	"\vGetAllNotes\x12\x18.note.GetAllNotesRequest\x1a\x19.note.GetAllNotesResponse\x121\n" +
	"\n" +
	"CreateNote\x12\x17.note.CreateNoteRequest\x1a\n" +
	".note.Note\x123\n" +
	"\vGetNoteById\x12\x18.note.GetNoteByIdRequest\x1a\n" +
	".note.Note\x12A\n" +
	"\x12GetNoteByShareUUID\x12\x1f.note.GetNoteByShareUUIDRequest\x1a\n" +
	".note.Note\x121\n" +
	"\n" +
	"UpdateNote\x12\x17.note.UpdateNoteRequest\x1a\n" +
	".note.Note\x12=\n" +
	"\n" +
	"DeleteNote\x12\x17.note.DeleteNoteRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\vAddFavorite\x12\x15.note.FavoriteRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\x0eRemoveFavorite\x12\x15.note.FavoriteRequest\x1a\x16.google.protobuf.EmptyB#Z!backend/notes_service/pkg/note/v1b\x06proto3"

var (
	file_proto_note_v1_note_proto_rawDescOnce sync.Once
	file_proto_note_v1_note_proto_rawDescData []byte
)

func file_proto_note_v1_note_proto_rawDescGZIP() []byte {
	file_proto_note_v1_note_proto_rawDescOnce.Do(func() {
		file_proto_note_v1_note_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_note_v1_note_proto_rawDesc), len(file_proto_note_v1_note_proto_rawDesc)))
	})
	return file_proto_note_v1_note_proto_rawDescData
}

var file_proto_note_v1_note_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_note_v1_note_proto_goTypes = []any{
	(*Note)(nil),                      // 0: note.Note
	(*GetAllNotesRequest)(nil),        // 1: note.GetAllNotesRequest
	(*GetAllNotesResponse)(nil),       // 2: note.GetAllNotesResponse
	(*CreateNoteRequest)(nil),         // 3: note.CreateNoteRequest
	(*GetNoteByIdRequest)(nil),        // 4: note.GetNoteByIdRequest
	(*GetNoteByShareUUIDRequest)(nil), // 5: note.GetNoteByShareUUIDRequest
	(*UpdateNoteRequest)(nil),         // 6: note.UpdateNoteRequest
	(*DeleteNoteRequest)(nil),         // 7: note.DeleteNoteRequest
	(*FavoriteRequest)(nil),           // 8: note.FavoriteRequest
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 10: google.protobuf.Empty
}
var file_proto_note_v1_note_proto_depIdxs = []int32{
	9,  // 0: note.Note.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: note.Note.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 2: note.Note.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: note.GetAllNotesResponse.notes:type_name -> note.Note
	1,  // 4: note.NoteService.GetAllNotes:input_type -> note.GetAllNotesRequest
	3,  // 5: note.NoteService.CreateNote:input_type -> note.CreateNoteRequest
	4,  // 6: note.NoteService.GetNoteById:input_type -> note.GetNoteByIdRequest
	5,  // 7: note.NoteService.GetNoteByShareUUID:input_type -> note.GetNoteByShareUUIDRequest
	6,  // 8: note.NoteService.UpdateNote:input_type -> note.UpdateNoteRequest
	7,  // 9: note.NoteService.DeleteNote:input_type -> note.DeleteNoteRequest
	8,  // 10: note.NoteService.AddFavorite:input_type -> note.FavoriteRequest
	8,  // 11: note.NoteService.RemoveFavorite:input_type -> note.FavoriteRequest
	2,  // 12: note.NoteService.GetAllNotes:output_type -> note.GetAllNotesResponse
	0,  // 13: note.NoteService.CreateNote:output_type -> note.Note
	0,  // 14: note.NoteService.GetNoteById:output_type -> note.Note
	0,  // 15: note.NoteService.GetNoteByShareUUID:output_type -> note.Note
	0,  // 16: note.NoteService.UpdateNote:output_type -> note.Note
	10, // 17: note.NoteService.DeleteNote:output_type -> google.protobuf.Empty
	10, // 18: note.NoteService.AddFavorite:output_type -> google.protobuf.Empty
	10, // 19: note.NoteService.RemoveFavorite:output_type -> google.protobuf.Empty
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_note_v1_note_proto_init() }
func file_proto_note_v1_note_proto_init() {
	if File_proto_note_v1_note_proto != nil {
		return
	}
	file_proto_note_v1_note_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_note_v1_note_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_note_v1_note_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_note_v1_note_proto_rawDesc), len(file_proto_note_v1_note_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_note_v1_note_proto_goTypes,
		DependencyIndexes: file_proto_note_v1_note_proto_depIdxs,
		MessageInfos:      file_proto_note_v1_note_proto_msgTypes,
	}.Build()
	File_proto_note_v1_note_proto = out.File
	file_proto_note_v1_note_proto_goTypes = nil
	file_proto_note_v1_note_proto_depIdxs = nil
}
