{
 "title": "Goose Metrics",
 "tags": [
  "microservices",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Datasource", "query": "prometheus" },
   { "name": "service", "query": "gateway, auth, notes, user" },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{service=~\"$service\"}[$interval])",
     "legendFormat": "{{service}} - {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Errors Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_errors_total{service=~\"$service\"}[$interval])",
     "legendFormat": "{{service}} - {{method}} {{path}} - {{code}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{service=~\"$service\"}[$interval]))",
     "legendFormat": "p95 - {{service}} - {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "gRPC Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(grpc_requests_total{service=~\"$service\",method!=\"/dummy/method\"}[$interval])",
     "legendFormat": "{{service}} - {{method}}"
    }
   ]
  },
  {
   "title": "gRPC Errors Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(grpc_errors_total{service=~\"$service\",method!=\"/dummy/method\"}[$interval])",
     "legendFormat": "{{service}} - {{method}} - code:{{code}}"
    }
   ]
  },
  {
   "title": "gRPC Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(grpc_request_duration_seconds_bucket{service=~\"$service\",method!=\"/dummy/method\"}[$interval]))",
     "legendFormat": "p95 - {{service}} - {{method}}"
    }
   ]
  },
  {
   "title": "DB Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(db_query_duration_seconds_bucket[${interval:raw}])) by (le, operation, table))",
     "legendFormat": "p95 - {{operation}} - {{table}}"
    }
   ]
  },
  {
   "title": "DB Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(db_query_errors_total[${interval:raw}])) by (operation, table)",
     "legendFormat": "{{operation}} - {{table}}"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (service, instance) (rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (sum by (service, instance) (node_memory_MemAvailable_bytes{job=\"node-exporter\"}) / sum by (service, instance) (node_memory_MemTotal_bytes{job=\"node-exporter\"}))) * 100",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "System Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum by (service, instance) (node_filesystem_size_bytes{job=\"node-exporter\",fstype!~\"tmpfs|rootfs\",device!~\"rootfs\",mountpoint!~\"^/(sys|proc|dev|run|tmp)($|/)\"}) - sum by (service, instance) (node_filesystem_avail_bytes{job=\"node-exporter\",fstype!~\"tmpfs|rootfs\",device!~\"rootfs\",mountpoint!~\"^/(sys|proc|dev|run|tmp)($|/)\"})) / sum by (service, instance) (node_filesystem_size_bytes{job=\"node-exporter\",fstype!~\"tmpfs|rootfs\",device!~\"rootfs\",mountpoint!~\"^/(sys|proc|dev|run|tmp)($|/)\"})) * 100",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}