// Code generated by MockGen. DO NOT EDIT.
// Source: notes/delivery/delivery.go
//
// Generated by this command:
//
//	mockgen -source=notes/delivery/delivery.go -destination=notes/mock/mock_delivery.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	models "backend/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotesUsecase is a mock of NotesUsecase interface.
type MockNotesUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockNotesUsecaseMockRecorder
	isgomock struct{}
}

// MockNotesUsecaseMockRecorder is the mock recorder for MockNotesUsecase.
type MockNotesUsecaseMockRecorder struct {
	mock *MockNotesUsecase
}

// NewMockNotesUsecase creates a new mock instance.
func NewMockNotesUsecase(ctrl *gomock.Controller) *MockNotesUsecase {
	mock := &MockNotesUsecase{ctrl: ctrl}
	mock.recorder = &MockNotesUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotesUsecase) EXPECT() *MockNotesUsecaseMockRecorder {
	return m.recorder
}

// CreateNote mocks base method.
func (m *MockNotesUsecase) CreateNote(ctx context.Context, userID uint64) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, userID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNotesUsecaseMockRecorder) CreateNote(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNotesUsecase)(nil).CreateNote), ctx, userID)
}

// DeleteNote mocks base method.
func (m *MockNotesUsecase) DeleteNote(ctx context.Context, userID, noteID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, userID, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockNotesUsecaseMockRecorder) DeleteNote(ctx, userID, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockNotesUsecase)(nil).DeleteNote), ctx, userID, noteID)
}

// GetAllNotes mocks base method.
func (m *MockNotesUsecase) GetAllNotes(ctx context.Context, userID uint64) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNotes", ctx, userID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotes indicates an expected call of GetAllNotes.
func (mr *MockNotesUsecaseMockRecorder) GetAllNotes(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotes", reflect.TypeOf((*MockNotesUsecase)(nil).GetAllNotes), ctx, userID)
}

// GetNoteById mocks base method.
func (m *MockNotesUsecase) GetNoteById(ctx context.Context, userID, noteID uint64) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteById", ctx, userID, noteID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteById indicates an expected call of GetNoteById.
func (mr *MockNotesUsecaseMockRecorder) GetNoteById(ctx, userID, noteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteById", reflect.TypeOf((*MockNotesUsecase)(nil).GetNoteById), ctx, userID, noteID)
}

// UpdateNote mocks base method.
func (m *MockNotesUsecase) UpdateNote(ctx context.Context, userID, noteID uint64, title *string, isArchived *bool) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, userID, noteID, title, isArchived)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockNotesUsecaseMockRecorder) UpdateNote(ctx, userID, noteID, title, isArchived any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockNotesUsecase)(nil).UpdateNote), ctx, userID, noteID, title, isArchived)
}
