// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/sharing/v1/sharing.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoteRole int32

const (
	NoteRole_NOTE_ROLE_UNSPECIFIED NoteRole = 0
	NoteRole_NOTE_ROLE_OWNER       NoteRole = 1
	NoteRole_NOTE_ROLE_EDITOR      NoteRole = 2
	NoteRole_NOTE_ROLE_COMMENTER   NoteRole = 3
	NoteRole_NOTE_ROLE_VIEWER      NoteRole = 4
)

// Enum value maps for NoteRole.
var (
	NoteRole_name = map[int32]string{
		0: "NOTE_ROLE_UNSPECIFIED",
		1: "NOTE_ROLE_OWNER",
		2: "NOTE_ROLE_EDITOR",
		3: "NOTE_ROLE_COMMENTER",
		4: "NOTE_ROLE_VIEWER",
	}
	NoteRole_value = map[string]int32{
		"NOTE_ROLE_UNSPECIFIED": 0,
		"NOTE_ROLE_OWNER":       1,
		"NOTE_ROLE_EDITOR":      2,
		"NOTE_ROLE_COMMENTER":   3,
		"NOTE_ROLE_VIEWER":      4,
	}
)

func (x NoteRole) Enum() *NoteRole {
	p := new(NoteRole)
	*p = x
	return p
}

func (x NoteRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NoteRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sharing_v1_sharing_proto_enumTypes[0].Descriptor()
}

func (NoteRole) Type() protoreflect.EnumType {
	return &file_proto_sharing_v1_sharing_proto_enumTypes[0]
}

func (x NoteRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NoteRole.Descriptor instead.
func (NoteRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{0}
}

type Collaborator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  uint64                 `protobuf:"varint,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          NoteRole               `protobuf:"varint,3,opt,name=role,proto3,enum=sharing.NoteRole" json:"role,omitempty"`
	GrantedBy     uint64                 `protobuf:"varint,4,opt,name=granted_by,json=grantedBy,proto3" json:"granted_by,omitempty"`
	GrantedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=granted_at,json=grantedAt,proto3" json:"granted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collaborator) Reset() {
	*x = Collaborator{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collaborator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collaborator) ProtoMessage() {}

func (x *Collaborator) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collaborator.ProtoReflect.Descriptor instead.
func (*Collaborator) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{0}
}

func (x *Collaborator) GetPermissionId() uint64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *Collaborator) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Collaborator) GetRole() NoteRole {
	if x != nil {
		return x.Role
	}
	return NoteRole_NOTE_ROLE_UNSPECIFIED
}

func (x *Collaborator) GetGrantedBy() uint64 {
	if x != nil {
		return x.GrantedBy
	}
	return 0
}

func (x *Collaborator) GetGrantedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GrantedAt
	}
	return nil
}

type PublicAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        uint64                 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	AccessLevel   *NoteRole              `protobuf:"varint,2,opt,name=access_level,json=accessLevel,proto3,enum=sharing.NoteRole,oneof" json:"access_level,omitempty"`
	ShareUrl      string                 `protobuf:"bytes,3,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicAccess) Reset() {
	*x = PublicAccess{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicAccess) ProtoMessage() {}

func (x *PublicAccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicAccess.ProtoReflect.Descriptor instead.
func (*PublicAccess) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{1}
}

func (x *PublicAccess) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *PublicAccess) GetAccessLevel() NoteRole {
	if x != nil && x.AccessLevel != nil {
		return *x.AccessLevel
	}
	return NoteRole_NOTE_ROLE_UNSPECIFIED
}

func (x *PublicAccess) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

type AddCollaboratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentUserId uint64                 `protobuf:"varint,1,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          NoteRole               `protobuf:"varint,4,opt,name=role,proto3,enum=sharing.NoteRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCollaboratorRequest) Reset() {
	*x = AddCollaboratorRequest{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCollaboratorRequest) ProtoMessage() {}

func (x *AddCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*AddCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{2}
}

func (x *AddCollaboratorRequest) GetCurrentUserId() uint64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

func (x *AddCollaboratorRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *AddCollaboratorRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCollaboratorRequest) GetRole() NoteRole {
	if x != nil {
		return x.Role
	}
	return NoteRole_NOTE_ROLE_UNSPECIFIED
}

type CollaboratorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PermissionId  uint64                 `protobuf:"varint,1,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	Collaborator  *Collaborator          `protobuf:"bytes,2,opt,name=collaborator,proto3" json:"collaborator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollaboratorResponse) Reset() {
	*x = CollaboratorResponse{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollaboratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollaboratorResponse) ProtoMessage() {}

func (x *CollaboratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollaboratorResponse.ProtoReflect.Descriptor instead.
func (*CollaboratorResponse) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{3}
}

func (x *CollaboratorResponse) GetPermissionId() uint64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *CollaboratorResponse) GetCollaborator() *Collaborator {
	if x != nil {
		return x.Collaborator
	}
	return nil
}

type GetCollaboratorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentUserId uint64                 `protobuf:"varint,1,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollaboratorsRequest) Reset() {
	*x = GetCollaboratorsRequest{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollaboratorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollaboratorsRequest) ProtoMessage() {}

func (x *GetCollaboratorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollaboratorsRequest.ProtoReflect.Descriptor instead.
func (*GetCollaboratorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{4}
}

func (x *GetCollaboratorsRequest) GetCurrentUserId() uint64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

func (x *GetCollaboratorsRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type GetCollaboratorsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NoteId             uint64                 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	OwnerId            uint64                 `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Collaborators      []*Collaborator        `protobuf:"bytes,3,rep,name=collaborators,proto3" json:"collaborators,omitempty"`
	PublicAccessLevel  *NoteRole              `protobuf:"varint,4,opt,name=public_access_level,json=publicAccessLevel,proto3,enum=sharing.NoteRole,oneof" json:"public_access_level,omitempty"`
	TotalCollaborators int32                  `protobuf:"varint,5,opt,name=total_collaborators,json=totalCollaborators,proto3" json:"total_collaborators,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetCollaboratorsResponse) Reset() {
	*x = GetCollaboratorsResponse{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollaboratorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollaboratorsResponse) ProtoMessage() {}

func (x *GetCollaboratorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollaboratorsResponse.ProtoReflect.Descriptor instead.
func (*GetCollaboratorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{5}
}

func (x *GetCollaboratorsResponse) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *GetCollaboratorsResponse) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *GetCollaboratorsResponse) GetCollaborators() []*Collaborator {
	if x != nil {
		return x.Collaborators
	}
	return nil
}

func (x *GetCollaboratorsResponse) GetPublicAccessLevel() NoteRole {
	if x != nil && x.PublicAccessLevel != nil {
		return *x.PublicAccessLevel
	}
	return NoteRole_NOTE_ROLE_UNSPECIFIED
}

func (x *GetCollaboratorsResponse) GetTotalCollaborators() int32 {
	if x != nil {
		return x.TotalCollaborators
	}
	return 0
}

type UpdateCollaboratorRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentUserId uint64                 `protobuf:"varint,1,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	PermissionId  uint64                 `protobuf:"varint,3,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	NewRole       NoteRole               `protobuf:"varint,4,opt,name=new_role,json=newRole,proto3,enum=sharing.NoteRole" json:"new_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollaboratorRoleRequest) Reset() {
	*x = UpdateCollaboratorRoleRequest{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollaboratorRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollaboratorRoleRequest) ProtoMessage() {}

func (x *UpdateCollaboratorRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollaboratorRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollaboratorRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCollaboratorRoleRequest) GetCurrentUserId() uint64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

func (x *UpdateCollaboratorRoleRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *UpdateCollaboratorRoleRequest) GetPermissionId() uint64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *UpdateCollaboratorRoleRequest) GetNewRole() NoteRole {
	if x != nil {
		return x.NewRole
	}
	return NoteRole_NOTE_ROLE_UNSPECIFIED
}

type RemoveCollaboratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentUserId uint64                 `protobuf:"varint,1,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	PermissionId  uint64                 `protobuf:"varint,3,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCollaboratorRequest) Reset() {
	*x = RemoveCollaboratorRequest{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCollaboratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCollaboratorRequest) ProtoMessage() {}

func (x *RemoveCollaboratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCollaboratorRequest.ProtoReflect.Descriptor instead.
func (*RemoveCollaboratorRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveCollaboratorRequest) GetCurrentUserId() uint64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

func (x *RemoveCollaboratorRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *RemoveCollaboratorRequest) GetPermissionId() uint64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

type SetPublicAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentUserId uint64                 `protobuf:"varint,1,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	AccessLevel   *NoteRole              `protobuf:"varint,3,opt,name=access_level,json=accessLevel,proto3,enum=sharing.NoteRole,oneof" json:"access_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPublicAccessRequest) Reset() {
	*x = SetPublicAccessRequest{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPublicAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPublicAccessRequest) ProtoMessage() {}

func (x *SetPublicAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPublicAccessRequest.ProtoReflect.Descriptor instead.
func (*SetPublicAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{8}
}

func (x *SetPublicAccessRequest) GetCurrentUserId() uint64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

func (x *SetPublicAccessRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *SetPublicAccessRequest) GetAccessLevel() NoteRole {
	if x != nil && x.AccessLevel != nil {
		return *x.AccessLevel
	}
	return NoteRole_NOTE_ROLE_UNSPECIFIED
}

type PublicAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        uint64                 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	AccessLevel   *NoteRole              `protobuf:"varint,2,opt,name=access_level,json=accessLevel,proto3,enum=sharing.NoteRole,oneof" json:"access_level,omitempty"`
	ShareUrl      string                 `protobuf:"bytes,3,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicAccessResponse) Reset() {
	*x = PublicAccessResponse{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicAccessResponse) ProtoMessage() {}

func (x *PublicAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicAccessResponse.ProtoReflect.Descriptor instead.
func (*PublicAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{9}
}

func (x *PublicAccessResponse) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *PublicAccessResponse) GetAccessLevel() NoteRole {
	if x != nil && x.AccessLevel != nil {
		return *x.AccessLevel
	}
	return NoteRole_NOTE_ROLE_UNSPECIFIED
}

func (x *PublicAccessResponse) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

func (x *PublicAccessResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetPublicAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentUserId uint64                 `protobuf:"varint,1,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicAccessRequest) Reset() {
	*x = GetPublicAccessRequest{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicAccessRequest) ProtoMessage() {}

func (x *GetPublicAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicAccessRequest.ProtoReflect.Descriptor instead.
func (*GetPublicAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{10}
}

func (x *GetPublicAccessRequest) GetCurrentUserId() uint64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

func (x *GetPublicAccessRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type GetSharingSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentUserId uint64                 `protobuf:"varint,1,opt,name=current_user_id,json=currentUserId,proto3" json:"current_user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSharingSettingsRequest) Reset() {
	*x = GetSharingSettingsRequest{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSharingSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSharingSettingsRequest) ProtoMessage() {}

func (x *GetSharingSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSharingSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSharingSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{11}
}

func (x *GetSharingSettingsRequest) GetCurrentUserId() uint64 {
	if x != nil {
		return x.CurrentUserId
	}
	return 0
}

func (x *GetSharingSettingsRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type SharingSettingsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NoteId             uint64                 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	OwnerId            uint64                 `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	PublicAccess       *PublicAccess          `protobuf:"bytes,3,opt,name=public_access,json=publicAccess,proto3" json:"public_access,omitempty"`
	Collaborators      []*Collaborator        `protobuf:"bytes,4,rep,name=collaborators,proto3" json:"collaborators,omitempty"`
	TotalCollaborators int32                  `protobuf:"varint,5,opt,name=total_collaborators,json=totalCollaborators,proto3" json:"total_collaborators,omitempty"`
	IsOwner            bool                   `protobuf:"varint,6,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SharingSettingsResponse) Reset() {
	*x = SharingSettingsResponse{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharingSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharingSettingsResponse) ProtoMessage() {}

func (x *SharingSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharingSettingsResponse.ProtoReflect.Descriptor instead.
func (*SharingSettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{12}
}

func (x *SharingSettingsResponse) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *SharingSettingsResponse) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *SharingSettingsResponse) GetPublicAccess() *PublicAccess {
	if x != nil {
		return x.PublicAccess
	}
	return nil
}

func (x *SharingSettingsResponse) GetCollaborators() []*Collaborator {
	if x != nil {
		return x.Collaborators
	}
	return nil
}

func (x *SharingSettingsResponse) GetTotalCollaborators() int32 {
	if x != nil {
		return x.TotalCollaborators
	}
	return 0
}

func (x *SharingSettingsResponse) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

type CheckNoteAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckNoteAccessRequest) Reset() {
	*x = CheckNoteAccessRequest{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckNoteAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckNoteAccessRequest) ProtoMessage() {}

func (x *CheckNoteAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckNoteAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckNoteAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{13}
}

func (x *CheckNoteAccessRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckNoteAccessRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type NoteAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAccess     bool                   `protobuf:"varint,1,opt,name=has_access,json=hasAccess,proto3" json:"has_access,omitempty"`
	Role          NoteRole               `protobuf:"varint,2,opt,name=role,proto3,enum=sharing.NoteRole" json:"role,omitempty"`
	IsOwner       bool                   `protobuf:"varint,3,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	CanEdit       bool                   `protobuf:"varint,4,opt,name=can_edit,json=canEdit,proto3" json:"can_edit,omitempty"`
	CanComment    bool                   `protobuf:"varint,5,opt,name=can_comment,json=canComment,proto3" json:"can_comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteAccessResponse) Reset() {
	*x = NoteAccessResponse{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteAccessResponse) ProtoMessage() {}

func (x *NoteAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteAccessResponse.ProtoReflect.Descriptor instead.
func (*NoteAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{14}
}

func (x *NoteAccessResponse) GetHasAccess() bool {
	if x != nil {
		return x.HasAccess
	}
	return false
}

func (x *NoteAccessResponse) GetRole() NoteRole {
	if x != nil {
		return x.Role
	}
	return NoteRole_NOTE_ROLE_UNSPECIFIED
}

func (x *NoteAccessResponse) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

func (x *NoteAccessResponse) GetCanEdit() bool {
	if x != nil {
		return x.CanEdit
	}
	return false
}

func (x *NoteAccessResponse) GetCanComment() bool {
	if x != nil {
		return x.CanComment
	}
	return false
}

type ActivateAccessByLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShareUuid     string                 `protobuf:"bytes,1,opt,name=share_uuid,json=shareUuid,proto3" json:"share_uuid,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateAccessByLinkRequest) Reset() {
	*x = ActivateAccessByLinkRequest{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateAccessByLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateAccessByLinkRequest) ProtoMessage() {}

func (x *ActivateAccessByLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateAccessByLinkRequest.ProtoReflect.Descriptor instead.
func (*ActivateAccessByLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{15}
}

func (x *ActivateAccessByLinkRequest) GetShareUuid() string {
	if x != nil {
		return x.ShareUuid
	}
	return ""
}

func (x *ActivateAccessByLinkRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ActivateAccessByLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        uint64                 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	AccessGranted bool                   `protobuf:"varint,2,opt,name=access_granted,json=accessGranted,proto3" json:"access_granted,omitempty"`
	AccessInfo    *NoteAccessResponse    `protobuf:"bytes,3,opt,name=access_info,json=accessInfo,proto3" json:"access_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateAccessByLinkResponse) Reset() {
	*x = ActivateAccessByLinkResponse{}
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateAccessByLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateAccessByLinkResponse) ProtoMessage() {}

func (x *ActivateAccessByLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sharing_v1_sharing_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateAccessByLinkResponse.ProtoReflect.Descriptor instead.
func (*ActivateAccessByLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_sharing_v1_sharing_proto_rawDescGZIP(), []int{16}
}

func (x *ActivateAccessByLinkResponse) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *ActivateAccessByLinkResponse) GetAccessGranted() bool {
	if x != nil {
		return x.AccessGranted
	}
	return false
}

func (x *ActivateAccessByLinkResponse) GetAccessInfo() *NoteAccessResponse {
	if x != nil {
		return x.AccessInfo
	}
	return nil
}

var File_proto_sharing_v1_sharing_proto protoreflect.FileDescriptor

const file_proto_sharing_v1_sharing_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/sharing/v1/sharing.proto\x12\asharing\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xcd\x01\n" +
	"\fCollaborator\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\x04R\fpermissionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12%\n" +
	"\x04role\x18\x03 \x01(\x0e2\x11.sharing.NoteRoleR\x04role\x12\x1d\n" +
	"\n" +
	"granted_by\x18\x04 \x01(\x04R\tgrantedBy\x129\n" +
	"\n" +
	"granted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tgrantedAt\"\x90\x01\n" +
	"\fPublicAccess\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x04R\x06noteId\x129\n" +
	"\faccess_level\x18\x02 \x01(\x0e2\x11.sharing.NoteRoleH\x00R\vaccessLevel\x88\x01\x01\x12\x1b\n" +
	"\tshare_url\x18\x03 \x01(\tR\bshareUrlB\x0f\n" +
	"\r_access_level\"\x99\x01\n" +
	"\x16AddCollaboratorRequest\x12&\n" +
	"\x0fcurrent_user_id\x18\x01 \x01(\x04R\rcurrentUserId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12%\n" +
	"\x04role\x18\x04 \x01(\x0e2\x11.sharing.NoteRoleR\x04role\"v\n" +
	"\x14CollaboratorResponse\x12#\n" +
	"\rpermission_id\x18\x01 \x01(\x04R\fpermissionId\x129\n" +
	"\fcollaborator\x18\x02 \x01(\v2\x15.sharing.CollaboratorR\fcollaborator\"Z\n" +
	"\x17GetCollaboratorsRequest\x12&\n" +
	"\x0fcurrent_user_id\x18\x01 \x01(\x04R\rcurrentUserId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\"\x9c\x02\n" +
	"\x18GetCollaboratorsResponse\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x04R\x06noteId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x04R\aownerId\x12;\n" +
	"\rcollaborators\x18\x03 \x03(\v2\x15.sharing.CollaboratorR\rcollaborators\x12F\n" +
	"\x13public_access_level\x18\x04 \x01(\x0e2\x11.sharing.NoteRoleH\x00R\x11publicAccessLevel\x88\x01\x01\x12/\n" +
	"\x13total_collaborators\x18\x05 \x01(\x05R\x12totalCollaboratorsB\x16\n" +
	"\x14_public_access_level\"\xb3\x01\n" +
	"\x1dUpdateCollaboratorRoleRequest\x12&\n" +
	"\x0fcurrent_user_id\x18\x01 \x01(\x04R\rcurrentUserId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\x12#\n" +
	"\rpermission_id\x18\x03 \x01(\x04R\fpermissionId\x12,\n" +
	"\bnew_role\x18\x04 \x01(\x0e2\x11.sharing.NoteRoleR\anewRole\"\x81\x01\n" +
	"\x19RemoveCollaboratorRequest\x12&\n" +
	"\x0fcurrent_user_id\x18\x01 \x01(\x04R\rcurrentUserId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\x12#\n" +
	"\rpermission_id\x18\x03 \x01(\x04R\fpermissionId\"\xa5\x01\n" +
	"\x16SetPublicAccessRequest\x12&\n" +
	"\x0fcurrent_user_id\x18\x01 \x01(\x04R\rcurrentUserId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\x129\n" +
	"\faccess_level\x18\x03 \x01(\x0e2\x11.sharing.NoteRoleH\x00R\vaccessLevel\x88\x01\x01B\x0f\n" +
	"\r_access_level\"\xd3\x01\n" +
	"\x14PublicAccessResponse\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x04R\x06noteId\x129\n" +
	"\faccess_level\x18\x02 \x01(\x0e2\x11.sharing.NoteRoleH\x00R\vaccessLevel\x88\x01\x01\x12\x1b\n" +
	"\tshare_url\x18\x03 \x01(\tR\bshareUrl\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0f\n" +
	"\r_access_level\"Y\n" +
	"\x16GetPublicAccessRequest\x12&\n" +
	"\x0fcurrent_user_id\x18\x01 \x01(\x04R\rcurrentUserId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\"\\\n" +
	"\x19GetSharingSettingsRequest\x12&\n" +
	"\x0fcurrent_user_id\x18\x01 \x01(\x04R\rcurrentUserId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\"\x92\x02\n" +
	"\x17SharingSettingsResponse\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x04R\x06noteId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x04R\aownerId\x12:\n" +
	"\rpublic_access\x18\x03 \x01(\v2\x15.sharing.PublicAccessR\fpublicAccess\x12;\n" +
	"\rcollaborators\x18\x04 \x03(\v2\x15.sharing.CollaboratorR\rcollaborators\x12/\n" +
	"\x13total_collaborators\x18\x05 \x01(\x05R\x12totalCollaborators\x12\x19\n" +
	"\bis_owner\x18\x06 \x01(\bR\aisOwner\"J\n" +
	"\x16CheckNoteAccessRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\"\xb1\x01\n" +
	"\x12NoteAccessResponse\x12\x1d\n" +
	"\n" +
	"has_access\x18\x01 \x01(\bR\thasAccess\x12%\n" +
	"\x04role\x18\x02 \x01(\x0e2\x11.sharing.NoteRoleR\x04role\x12\x19\n" +
	"\bis_owner\x18\x03 \x01(\bR\aisOwner\x12\x19\n" +
	"\bcan_edit\x18\x04 \x01(\bR\acanEdit\x12\x1f\n" +
	"\vcan_comment\x18\x05 \x01(\bR\n" +
	"canComment\"U\n" +
	"\x1bActivateAccessByLinkRequest\x12\x1d\n" +
	"\n" +
	"share_uuid\x18\x01 \x01(\tR\tshareUuid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\x9c\x01\n" +
	"\x1cActivateAccessByLinkResponse\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\x04R\x06noteId\x12%\n" +
	"\x0eaccess_granted\x18\x02 \x01(\bR\raccessGranted\x12<\n" +
	"\vaccess_info\x18\x03 \x01(\v2\x1b.sharing.NoteAccessResponseR\n" +
	"accessInfo*\x7f\n" +
	"\bNoteRole\x12\x19\n" +
	"\x15NOTE_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fNOTE_ROLE_OWNER\x10\x01\x12\x14\n" +
	"\x10NOTE_ROLE_EDITOR\x10\x02\x12\x17\n" +
	"\x13NOTE_ROLE_COMMENTER\x10\x03\x12\x14\n" +
	"\x10NOTE_ROLE_VIEWER\x10\x042\xa7\x06\n" +
	"\x0eSharingService\x12Q\n" +
	"\x0fAddCollaborator\x12\x1f.sharing.AddCollaboratorRequest\x1a\x1d.sharing.CollaboratorResponse\x12W\n" +
	"\x10GetCollaborators\x12 .sharing.GetCollaboratorsRequest\x1a!.sharing.GetCollaboratorsResponse\x12_\n" +
	"\x16UpdateCollaboratorRole\x12&.sharing.UpdateCollaboratorRoleRequest\x1a\x1d.sharing.CollaboratorResponse\x12P\n" +
	"\x12RemoveCollaborator\x12\".sharing.RemoveCollaboratorRequest\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x0fSetPublicAccess\x12\x1f.sharing.SetPublicAccessRequest\x1a\x1d.sharing.PublicAccessResponse\x12Q\n" +
	"\x0fGetPublicAccess\x12\x1f.sharing.GetPublicAccessRequest\x1a\x1d.sharing.PublicAccessResponse\x12Z\n" +
	"\x12GetSharingSettings\x12\".sharing.GetSharingSettingsRequest\x1a .sharing.SharingSettingsResponse\x12O\n" +
	"\x0fCheckNoteAccess\x12\x1f.sharing.CheckNoteAccessRequest\x1a\x1b.sharing.NoteAccessResponse\x12c\n" +
	"\x14ActivateAccessByLink\x12$.sharing.ActivateAccessByLinkRequest\x1a%.sharing.ActivateAccessByLinkResponseB&Z$backend/notes_service/pkg/sharing/v1b\x06proto3"

var (
	file_proto_sharing_v1_sharing_proto_rawDescOnce sync.Once
	file_proto_sharing_v1_sharing_proto_rawDescData []byte
)

func file_proto_sharing_v1_sharing_proto_rawDescGZIP() []byte {
	file_proto_sharing_v1_sharing_proto_rawDescOnce.Do(func() {
		file_proto_sharing_v1_sharing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sharing_v1_sharing_proto_rawDesc), len(file_proto_sharing_v1_sharing_proto_rawDesc)))
	})
	return file_proto_sharing_v1_sharing_proto_rawDescData
}

var file_proto_sharing_v1_sharing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_sharing_v1_sharing_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_sharing_v1_sharing_proto_goTypes = []any{
	(NoteRole)(0),                         // 0: sharing.NoteRole
	(*Collaborator)(nil),                  // 1: sharing.Collaborator
	(*PublicAccess)(nil),                  // 2: sharing.PublicAccess
	(*AddCollaboratorRequest)(nil),        // 3: sharing.AddCollaboratorRequest
	(*CollaboratorResponse)(nil),          // 4: sharing.CollaboratorResponse
	(*GetCollaboratorsRequest)(nil),       // 5: sharing.GetCollaboratorsRequest
	(*GetCollaboratorsResponse)(nil),      // 6: sharing.GetCollaboratorsResponse
	(*UpdateCollaboratorRoleRequest)(nil), // 7: sharing.UpdateCollaboratorRoleRequest
	(*RemoveCollaboratorRequest)(nil),     // 8: sharing.RemoveCollaboratorRequest
	(*SetPublicAccessRequest)(nil),        // 9: sharing.SetPublicAccessRequest
	(*PublicAccessResponse)(nil),          // 10: sharing.PublicAccessResponse
	(*GetPublicAccessRequest)(nil),        // 11: sharing.GetPublicAccessRequest
	(*GetSharingSettingsRequest)(nil),     // 12: sharing.GetSharingSettingsRequest
	(*SharingSettingsResponse)(nil),       // 13: sharing.SharingSettingsResponse
	(*CheckNoteAccessRequest)(nil),        // 14: sharing.CheckNoteAccessRequest
	(*NoteAccessResponse)(nil),            // 15: sharing.NoteAccessResponse
	(*ActivateAccessByLinkRequest)(nil),   // 16: sharing.ActivateAccessByLinkRequest
	(*ActivateAccessByLinkResponse)(nil),  // 17: sharing.ActivateAccessByLinkResponse
	(*timestamppb.Timestamp)(nil),         // 18: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 19: google.protobuf.Empty
}
var file_proto_sharing_v1_sharing_proto_depIdxs = []int32{
	0,  // 0: sharing.Collaborator.role:type_name -> sharing.NoteRole
	18, // 1: sharing.Collaborator.granted_at:type_name -> google.protobuf.Timestamp
	0,  // 2: sharing.PublicAccess.access_level:type_name -> sharing.NoteRole
	0,  // 3: sharing.AddCollaboratorRequest.role:type_name -> sharing.NoteRole
	1,  // 4: sharing.CollaboratorResponse.collaborator:type_name -> sharing.Collaborator
	1,  // 5: sharing.GetCollaboratorsResponse.collaborators:type_name -> sharing.Collaborator
	0,  // 6: sharing.GetCollaboratorsResponse.public_access_level:type_name -> sharing.NoteRole
	0,  // 7: sharing.UpdateCollaboratorRoleRequest.new_role:type_name -> sharing.NoteRole
	0,  // 8: sharing.SetPublicAccessRequest.access_level:type_name -> sharing.NoteRole
	0,  // 9: sharing.PublicAccessResponse.access_level:type_name -> sharing.NoteRole
	18, // 10: sharing.PublicAccessResponse.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 11: sharing.SharingSettingsResponse.public_access:type_name -> sharing.PublicAccess
	1,  // 12: sharing.SharingSettingsResponse.collaborators:type_name -> sharing.Collaborator
	0,  // 13: sharing.NoteAccessResponse.role:type_name -> sharing.NoteRole
	15, // 14: sharing.ActivateAccessByLinkResponse.access_info:type_name -> sharing.NoteAccessResponse
	3,  // 15: sharing.SharingService.AddCollaborator:input_type -> sharing.AddCollaboratorRequest
	5,  // 16: sharing.SharingService.GetCollaborators:input_type -> sharing.GetCollaboratorsRequest
	7,  // 17: sharing.SharingService.UpdateCollaboratorRole:input_type -> sharing.UpdateCollaboratorRoleRequest
	8,  // 18: sharing.SharingService.RemoveCollaborator:input_type -> sharing.RemoveCollaboratorRequest
	9,  // 19: sharing.SharingService.SetPublicAccess:input_type -> sharing.SetPublicAccessRequest
	11, // 20: sharing.SharingService.GetPublicAccess:input_type -> sharing.GetPublicAccessRequest
	12, // 21: sharing.SharingService.GetSharingSettings:input_type -> sharing.GetSharingSettingsRequest
	14, // 22: sharing.SharingService.CheckNoteAccess:input_type -> sharing.CheckNoteAccessRequest
	16, // 23: sharing.SharingService.ActivateAccessByLink:input_type -> sharing.ActivateAccessByLinkRequest
	4,  // 24: sharing.SharingService.AddCollaborator:output_type -> sharing.CollaboratorResponse
	6,  // 25: sharing.SharingService.GetCollaborators:output_type -> sharing.GetCollaboratorsResponse
	4,  // 26: sharing.SharingService.UpdateCollaboratorRole:output_type -> sharing.CollaboratorResponse
	19, // 27: sharing.SharingService.RemoveCollaborator:output_type -> google.protobuf.Empty
	10, // 28: sharing.SharingService.SetPublicAccess:output_type -> sharing.PublicAccessResponse
	10, // 29: sharing.SharingService.GetPublicAccess:output_type -> sharing.PublicAccessResponse
	13, // 30: sharing.SharingService.GetSharingSettings:output_type -> sharing.SharingSettingsResponse
	15, // 31: sharing.SharingService.CheckNoteAccess:output_type -> sharing.NoteAccessResponse
	17, // 32: sharing.SharingService.ActivateAccessByLink:output_type -> sharing.ActivateAccessByLinkResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_sharing_v1_sharing_proto_init() }
func file_proto_sharing_v1_sharing_proto_init() {
	if File_proto_sharing_v1_sharing_proto != nil {
		return
	}
	file_proto_sharing_v1_sharing_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_sharing_v1_sharing_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_sharing_v1_sharing_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_sharing_v1_sharing_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sharing_v1_sharing_proto_rawDesc), len(file_proto_sharing_v1_sharing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sharing_v1_sharing_proto_goTypes,
		DependencyIndexes: file_proto_sharing_v1_sharing_proto_depIdxs,
		EnumInfos:         file_proto_sharing_v1_sharing_proto_enumTypes,
		MessageInfos:      file_proto_sharing_v1_sharing_proto_msgTypes,
	}.Build()
	File_proto_sharing_v1_sharing_proto = out.File
	file_proto_sharing_v1_sharing_proto_goTypes = nil
	file_proto_sharing_v1_sharing_proto_depIdxs = nil
}
