// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/sharing/v1/sharing.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SharingService_AddCollaborator_FullMethodName        = "/sharing.SharingService/AddCollaborator"
	SharingService_GetCollaborators_FullMethodName       = "/sharing.SharingService/GetCollaborators"
	SharingService_UpdateCollaboratorRole_FullMethodName = "/sharing.SharingService/UpdateCollaboratorRole"
	SharingService_RemoveCollaborator_FullMethodName     = "/sharing.SharingService/RemoveCollaborator"
	SharingService_SetPublicAccess_FullMethodName        = "/sharing.SharingService/SetPublicAccess"
	SharingService_GetPublicAccess_FullMethodName        = "/sharing.SharingService/GetPublicAccess"
	SharingService_GetSharingSettings_FullMethodName     = "/sharing.SharingService/GetSharingSettings"
	SharingService_CheckNoteAccess_FullMethodName        = "/sharing.SharingService/CheckNoteAccess"
	SharingService_ActivateAccessByLink_FullMethodName   = "/sharing.SharingService/ActivateAccessByLink"
)

// SharingServiceClient is the client API for SharingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SharingServiceClient interface {
	AddCollaborator(ctx context.Context, in *AddCollaboratorRequest, opts ...grpc.CallOption) (*CollaboratorResponse, error)
	GetCollaborators(ctx context.Context, in *GetCollaboratorsRequest, opts ...grpc.CallOption) (*GetCollaboratorsResponse, error)
	UpdateCollaboratorRole(ctx context.Context, in *UpdateCollaboratorRoleRequest, opts ...grpc.CallOption) (*CollaboratorResponse, error)
	RemoveCollaborator(ctx context.Context, in *RemoveCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetPublicAccess(ctx context.Context, in *SetPublicAccessRequest, opts ...grpc.CallOption) (*PublicAccessResponse, error)
	GetPublicAccess(ctx context.Context, in *GetPublicAccessRequest, opts ...grpc.CallOption) (*PublicAccessResponse, error)
	GetSharingSettings(ctx context.Context, in *GetSharingSettingsRequest, opts ...grpc.CallOption) (*SharingSettingsResponse, error)
	CheckNoteAccess(ctx context.Context, in *CheckNoteAccessRequest, opts ...grpc.CallOption) (*NoteAccessResponse, error)
	ActivateAccessByLink(ctx context.Context, in *ActivateAccessByLinkRequest, opts ...grpc.CallOption) (*ActivateAccessByLinkResponse, error)
}

type sharingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSharingServiceClient(cc grpc.ClientConnInterface) SharingServiceClient {
	return &sharingServiceClient{cc}
}

func (c *sharingServiceClient) AddCollaborator(ctx context.Context, in *AddCollaboratorRequest, opts ...grpc.CallOption) (*CollaboratorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollaboratorResponse)
	err := c.cc.Invoke(ctx, SharingService_AddCollaborator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharingServiceClient) GetCollaborators(ctx context.Context, in *GetCollaboratorsRequest, opts ...grpc.CallOption) (*GetCollaboratorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollaboratorsResponse)
	err := c.cc.Invoke(ctx, SharingService_GetCollaborators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharingServiceClient) UpdateCollaboratorRole(ctx context.Context, in *UpdateCollaboratorRoleRequest, opts ...grpc.CallOption) (*CollaboratorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollaboratorResponse)
	err := c.cc.Invoke(ctx, SharingService_UpdateCollaboratorRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharingServiceClient) RemoveCollaborator(ctx context.Context, in *RemoveCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SharingService_RemoveCollaborator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharingServiceClient) SetPublicAccess(ctx context.Context, in *SetPublicAccessRequest, opts ...grpc.CallOption) (*PublicAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicAccessResponse)
	err := c.cc.Invoke(ctx, SharingService_SetPublicAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharingServiceClient) GetPublicAccess(ctx context.Context, in *GetPublicAccessRequest, opts ...grpc.CallOption) (*PublicAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicAccessResponse)
	err := c.cc.Invoke(ctx, SharingService_GetPublicAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharingServiceClient) GetSharingSettings(ctx context.Context, in *GetSharingSettingsRequest, opts ...grpc.CallOption) (*SharingSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SharingSettingsResponse)
	err := c.cc.Invoke(ctx, SharingService_GetSharingSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharingServiceClient) CheckNoteAccess(ctx context.Context, in *CheckNoteAccessRequest, opts ...grpc.CallOption) (*NoteAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteAccessResponse)
	err := c.cc.Invoke(ctx, SharingService_CheckNoteAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sharingServiceClient) ActivateAccessByLink(ctx context.Context, in *ActivateAccessByLinkRequest, opts ...grpc.CallOption) (*ActivateAccessByLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateAccessByLinkResponse)
	err := c.cc.Invoke(ctx, SharingService_ActivateAccessByLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SharingServiceServer is the server API for SharingService service.
// All implementations must embed UnimplementedSharingServiceServer
// for forward compatibility.
type SharingServiceServer interface {
	AddCollaborator(context.Context, *AddCollaboratorRequest) (*CollaboratorResponse, error)
	GetCollaborators(context.Context, *GetCollaboratorsRequest) (*GetCollaboratorsResponse, error)
	UpdateCollaboratorRole(context.Context, *UpdateCollaboratorRoleRequest) (*CollaboratorResponse, error)
	RemoveCollaborator(context.Context, *RemoveCollaboratorRequest) (*emptypb.Empty, error)
	SetPublicAccess(context.Context, *SetPublicAccessRequest) (*PublicAccessResponse, error)
	GetPublicAccess(context.Context, *GetPublicAccessRequest) (*PublicAccessResponse, error)
	GetSharingSettings(context.Context, *GetSharingSettingsRequest) (*SharingSettingsResponse, error)
	CheckNoteAccess(context.Context, *CheckNoteAccessRequest) (*NoteAccessResponse, error)
	ActivateAccessByLink(context.Context, *ActivateAccessByLinkRequest) (*ActivateAccessByLinkResponse, error)
	mustEmbedUnimplementedSharingServiceServer()
}

// UnimplementedSharingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSharingServiceServer struct{}

func (UnimplementedSharingServiceServer) AddCollaborator(context.Context, *AddCollaboratorRequest) (*CollaboratorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCollaborator not implemented")
}
func (UnimplementedSharingServiceServer) GetCollaborators(context.Context, *GetCollaboratorsRequest) (*GetCollaboratorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollaborators not implemented")
}
func (UnimplementedSharingServiceServer) UpdateCollaboratorRole(context.Context, *UpdateCollaboratorRoleRequest) (*CollaboratorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCollaboratorRole not implemented")
}
func (UnimplementedSharingServiceServer) RemoveCollaborator(context.Context, *RemoveCollaboratorRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveCollaborator not implemented")
}
func (UnimplementedSharingServiceServer) SetPublicAccess(context.Context, *SetPublicAccessRequest) (*PublicAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPublicAccess not implemented")
}
func (UnimplementedSharingServiceServer) GetPublicAccess(context.Context, *GetPublicAccessRequest) (*PublicAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicAccess not implemented")
}
func (UnimplementedSharingServiceServer) GetSharingSettings(context.Context, *GetSharingSettingsRequest) (*SharingSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSharingSettings not implemented")
}
func (UnimplementedSharingServiceServer) CheckNoteAccess(context.Context, *CheckNoteAccessRequest) (*NoteAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckNoteAccess not implemented")
}
func (UnimplementedSharingServiceServer) ActivateAccessByLink(context.Context, *ActivateAccessByLinkRequest) (*ActivateAccessByLinkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateAccessByLink not implemented")
}
func (UnimplementedSharingServiceServer) mustEmbedUnimplementedSharingServiceServer() {}
func (UnimplementedSharingServiceServer) testEmbeddedByValue()                        {}

// UnsafeSharingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SharingServiceServer will
// result in compilation errors.
type UnsafeSharingServiceServer interface {
	mustEmbedUnimplementedSharingServiceServer()
}

func RegisterSharingServiceServer(s grpc.ServiceRegistrar, srv SharingServiceServer) {
	// If the following call pancis, it indicates UnimplementedSharingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SharingService_ServiceDesc, srv)
}

func _SharingService_AddCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).AddCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_AddCollaborator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).AddCollaborator(ctx, req.(*AddCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharingService_GetCollaborators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollaboratorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).GetCollaborators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_GetCollaborators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).GetCollaborators(ctx, req.(*GetCollaboratorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharingService_UpdateCollaboratorRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCollaboratorRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).UpdateCollaboratorRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_UpdateCollaboratorRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).UpdateCollaboratorRole(ctx, req.(*UpdateCollaboratorRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharingService_RemoveCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).RemoveCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_RemoveCollaborator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).RemoveCollaborator(ctx, req.(*RemoveCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharingService_SetPublicAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPublicAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).SetPublicAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_SetPublicAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).SetPublicAccess(ctx, req.(*SetPublicAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharingService_GetPublicAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).GetPublicAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_GetPublicAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).GetPublicAccess(ctx, req.(*GetPublicAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharingService_GetSharingSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSharingSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).GetSharingSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_GetSharingSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).GetSharingSettings(ctx, req.(*GetSharingSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharingService_CheckNoteAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckNoteAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).CheckNoteAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_CheckNoteAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).CheckNoteAccess(ctx, req.(*CheckNoteAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SharingService_ActivateAccessByLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateAccessByLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharingServiceServer).ActivateAccessByLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SharingService_ActivateAccessByLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharingServiceServer).ActivateAccessByLink(ctx, req.(*ActivateAccessByLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SharingService_ServiceDesc is the grpc.ServiceDesc for SharingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SharingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sharing.SharingService",
	HandlerType: (*SharingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCollaborator",
			Handler:    _SharingService_AddCollaborator_Handler,
		},
		{
			MethodName: "GetCollaborators",
			Handler:    _SharingService_GetCollaborators_Handler,
		},
		{
			MethodName: "UpdateCollaboratorRole",
			Handler:    _SharingService_UpdateCollaboratorRole_Handler,
		},
		{
			MethodName: "RemoveCollaborator",
			Handler:    _SharingService_RemoveCollaborator_Handler,
		},
		{
			MethodName: "SetPublicAccess",
			Handler:    _SharingService_SetPublicAccess_Handler,
		},
		{
			MethodName: "GetPublicAccess",
			Handler:    _SharingService_GetPublicAccess_Handler,
		},
		{
			MethodName: "GetSharingSettings",
			Handler:    _SharingService_GetSharingSettings_Handler,
		},
		{
			MethodName: "CheckNoteAccess",
			Handler:    _SharingService_CheckNoteAccess_Handler,
		},
		{
			MethodName: "ActivateAccessByLink",
			Handler:    _SharingService_ActivateAccessByLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sharing/v1/sharing.proto",
}
