// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	models "backend/gateway_service/internal/file/models"
	v1 "backend/notes_service/pkg/block/v1"
	v10 "backend/notes_service/pkg/note/v1"
	v11 "backend/notes_service/pkg/sharing/v1"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockFileRepository is a mock of FileRepository interface.
type MockFileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepositoryMockRecorder
}

// MockFileRepositoryMockRecorder is the mock recorder for MockFileRepository.
type MockFileRepositoryMockRecorder struct {
	mock *MockFileRepository
}

// NewMockFileRepository creates a new mock instance.
func NewMockFileRepository(ctrl *gomock.Controller) *MockFileRepository {
	mock := &MockFileRepository{ctrl: ctrl}
	mock.recorder = &MockFileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepository) EXPECT() *MockFileRepositoryMockRecorder {
	return m.recorder
}

// GetFileByID mocks base method.
func (m *MockFileRepository) GetFileByID(ctx context.Context, fileID uint64) (*models.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByID", ctx, fileID)
	ret0, _ := ret[0].(*models.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByID indicates an expected call of GetFileByID.
func (mr *MockFileRepositoryMockRecorder) GetFileByID(ctx, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByID", reflect.TypeOf((*MockFileRepository)(nil).GetFileByID), ctx, fileID)
}

// MockNoteClient is a mock of NoteClient interface.
type MockNoteClient struct {
	ctrl     *gomock.Controller
	recorder *MockNoteClientMockRecorder
}

// MockNoteClientMockRecorder is the mock recorder for MockNoteClient.
type MockNoteClientMockRecorder struct {
	mock *MockNoteClient
}

// NewMockNoteClient creates a new mock instance.
func NewMockNoteClient(ctrl *gomock.Controller) *MockNoteClient {
	mock := &MockNoteClient{ctrl: ctrl}
	mock.recorder = &MockNoteClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNoteClient) EXPECT() *MockNoteClientMockRecorder {
	return m.recorder
}

// AddFavorite mocks base method.
func (m *MockNoteClient) AddFavorite(ctx context.Context, in *v10.FavoriteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddFavorite", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFavorite indicates an expected call of AddFavorite.
func (mr *MockNoteClientMockRecorder) AddFavorite(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFavorite", reflect.TypeOf((*MockNoteClient)(nil).AddFavorite), varargs...)
}

// CreateNote mocks base method.
func (m *MockNoteClient) CreateNote(ctx context.Context, in *v10.CreateNoteRequest, opts ...grpc.CallOption) (*v10.Note, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateNote", varargs...)
	ret0, _ := ret[0].(*v10.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNoteClientMockRecorder) CreateNote(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNoteClient)(nil).CreateNote), varargs...)
}

// DeleteNote mocks base method.
func (m *MockNoteClient) DeleteNote(ctx context.Context, in *v10.DeleteNoteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteNote", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockNoteClientMockRecorder) DeleteNote(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockNoteClient)(nil).DeleteNote), varargs...)
}

// GetAllNotes mocks base method.
func (m *MockNoteClient) GetAllNotes(ctx context.Context, in *v10.GetAllNotesRequest, opts ...grpc.CallOption) (*v10.GetAllNotesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllNotes", varargs...)
	ret0, _ := ret[0].(*v10.GetAllNotesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNotes indicates an expected call of GetAllNotes.
func (mr *MockNoteClientMockRecorder) GetAllNotes(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNotes", reflect.TypeOf((*MockNoteClient)(nil).GetAllNotes), varargs...)
}

// GetNoteById mocks base method.
func (m *MockNoteClient) GetNoteById(ctx context.Context, in *v10.GetNoteByIdRequest, opts ...grpc.CallOption) (*v10.Note, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNoteById", varargs...)
	ret0, _ := ret[0].(*v10.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteById indicates an expected call of GetNoteById.
func (mr *MockNoteClientMockRecorder) GetNoteById(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteById", reflect.TypeOf((*MockNoteClient)(nil).GetNoteById), varargs...)
}

// RemoveFavorite mocks base method.
func (m *MockNoteClient) RemoveFavorite(ctx context.Context, in *v10.FavoriteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveFavorite", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveFavorite indicates an expected call of RemoveFavorite.
func (mr *MockNoteClientMockRecorder) RemoveFavorite(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFavorite", reflect.TypeOf((*MockNoteClient)(nil).RemoveFavorite), varargs...)
}

// SearchNotes mocks base method.
func (m *MockNoteClient) SearchNotes(ctx context.Context, in *v10.SearchNotesRequest, opts ...grpc.CallOption) (*v10.SearchNotesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchNotes", varargs...)
	ret0, _ := ret[0].(*v10.SearchNotesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchNotes indicates an expected call of SearchNotes.
func (mr *MockNoteClientMockRecorder) SearchNotes(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchNotes", reflect.TypeOf((*MockNoteClient)(nil).SearchNotes), varargs...)
}

// SetHeader mocks base method.
func (m *MockNoteClient) SetHeader(ctx context.Context, in *v10.SetHeaderRequest, opts ...grpc.CallOption) (*v10.Note, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetHeader", varargs...)
	ret0, _ := ret[0].(*v10.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockNoteClientMockRecorder) SetHeader(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockNoteClient)(nil).SetHeader), varargs...)
}

// SetIcon mocks base method.
func (m *MockNoteClient) SetIcon(ctx context.Context, in *v10.SetIconRequest, opts ...grpc.CallOption) (*v10.Note, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetIcon", varargs...)
	ret0, _ := ret[0].(*v10.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetIcon indicates an expected call of SetIcon.
func (mr *MockNoteClientMockRecorder) SetIcon(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIcon", reflect.TypeOf((*MockNoteClient)(nil).SetIcon), varargs...)
}

// UpdateNote mocks base method.
func (m *MockNoteClient) UpdateNote(ctx context.Context, in *v10.UpdateNoteRequest, opts ...grpc.CallOption) (*v10.Note, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateNote", varargs...)
	ret0, _ := ret[0].(*v10.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockNoteClientMockRecorder) UpdateNote(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockNoteClient)(nil).UpdateNote), varargs...)
}

// MockBlockClient is a mock of BlockClient interface.
type MockBlockClient struct {
	ctrl     *gomock.Controller
	recorder *MockBlockClientMockRecorder
}

// MockBlockClientMockRecorder is the mock recorder for MockBlockClient.
type MockBlockClientMockRecorder struct {
	mock *MockBlockClient
}

// NewMockBlockClient creates a new mock instance.
func NewMockBlockClient(ctrl *gomock.Controller) *MockBlockClient {
	mock := &MockBlockClient{ctrl: ctrl}
	mock.recorder = &MockBlockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockClient) EXPECT() *MockBlockClientMockRecorder {
	return m.recorder
}

// CreateAttachmentBlock mocks base method.
func (m *MockBlockClient) CreateAttachmentBlock(ctx context.Context, in *v1.CreateAttachmentBlockRequest, opts ...grpc.CallOption) (*v1.Block, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateAttachmentBlock", varargs...)
	ret0, _ := ret[0].(*v1.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttachmentBlock indicates an expected call of CreateAttachmentBlock.
func (mr *MockBlockClientMockRecorder) CreateAttachmentBlock(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttachmentBlock", reflect.TypeOf((*MockBlockClient)(nil).CreateAttachmentBlock), varargs...)
}

// CreateCodeBlock mocks base method.
func (m *MockBlockClient) CreateCodeBlock(ctx context.Context, in *v1.CreateCodeBlockRequest, opts ...grpc.CallOption) (*v1.Block, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCodeBlock", varargs...)
	ret0, _ := ret[0].(*v1.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCodeBlock indicates an expected call of CreateCodeBlock.
func (mr *MockBlockClientMockRecorder) CreateCodeBlock(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCodeBlock", reflect.TypeOf((*MockBlockClient)(nil).CreateCodeBlock), varargs...)
}

// CreateTextBlock mocks base method.
func (m *MockBlockClient) CreateTextBlock(ctx context.Context, in *v1.CreateTextBlockRequest, opts ...grpc.CallOption) (*v1.Block, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateTextBlock", varargs...)
	ret0, _ := ret[0].(*v1.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTextBlock indicates an expected call of CreateTextBlock.
func (mr *MockBlockClientMockRecorder) CreateTextBlock(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTextBlock", reflect.TypeOf((*MockBlockClient)(nil).CreateTextBlock), varargs...)
}

// DeleteBlock mocks base method.
func (m *MockBlockClient) DeleteBlock(ctx context.Context, in *v1.DeleteBlockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteBlock", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockBlockClientMockRecorder) DeleteBlock(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockBlockClient)(nil).DeleteBlock), varargs...)
}

// GetBlock mocks base method.
func (m *MockBlockClient) GetBlock(ctx context.Context, in *v1.GetBlockRequest, opts ...grpc.CallOption) (*v1.Block, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlock", varargs...)
	ret0, _ := ret[0].(*v1.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockBlockClientMockRecorder) GetBlock(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockBlockClient)(nil).GetBlock), varargs...)
}

// GetBlocks mocks base method.
func (m *MockBlockClient) GetBlocks(ctx context.Context, in *v1.GetBlocksRequest, opts ...grpc.CallOption) (*v1.GetBlocksResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlocks", varargs...)
	ret0, _ := ret[0].(*v1.GetBlocksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocks indicates an expected call of GetBlocks.
func (mr *MockBlockClientMockRecorder) GetBlocks(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocks", reflect.TypeOf((*MockBlockClient)(nil).GetBlocks), varargs...)
}

// UpdateBlock mocks base method.
func (m *MockBlockClient) UpdateBlock(ctx context.Context, in *v1.UpdateBlockRequest, opts ...grpc.CallOption) (*v1.Block, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBlock", varargs...)
	ret0, _ := ret[0].(*v1.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlock indicates an expected call of UpdateBlock.
func (mr *MockBlockClientMockRecorder) UpdateBlock(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlock", reflect.TypeOf((*MockBlockClient)(nil).UpdateBlock), varargs...)
}

// UpdateBlockPosition mocks base method.
func (m *MockBlockClient) UpdateBlockPosition(ctx context.Context, in *v1.UpdateBlockPositionRequest, opts ...grpc.CallOption) (*v1.Block, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateBlockPosition", varargs...)
	ret0, _ := ret[0].(*v1.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockPosition indicates an expected call of UpdateBlockPosition.
func (mr *MockBlockClientMockRecorder) UpdateBlockPosition(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockPosition", reflect.TypeOf((*MockBlockClient)(nil).UpdateBlockPosition), varargs...)
}

// MockSharingClient is a mock of SharingClient interface.
type MockSharingClient struct {
	ctrl     *gomock.Controller
	recorder *MockSharingClientMockRecorder
}

// MockSharingClientMockRecorder is the mock recorder for MockSharingClient.
type MockSharingClientMockRecorder struct {
	mock *MockSharingClient
}

// NewMockSharingClient creates a new mock instance.
func NewMockSharingClient(ctrl *gomock.Controller) *MockSharingClient {
	mock := &MockSharingClient{ctrl: ctrl}
	mock.recorder = &MockSharingClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSharingClient) EXPECT() *MockSharingClientMockRecorder {
	return m.recorder
}

// ActivateAccessByLink mocks base method.
func (m *MockSharingClient) ActivateAccessByLink(ctx context.Context, in *v11.ActivateAccessByLinkRequest, opts ...grpc.CallOption) (*v11.ActivateAccessByLinkResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ActivateAccessByLink", varargs...)
	ret0, _ := ret[0].(*v11.ActivateAccessByLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActivateAccessByLink indicates an expected call of ActivateAccessByLink.
func (mr *MockSharingClientMockRecorder) ActivateAccessByLink(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateAccessByLink", reflect.TypeOf((*MockSharingClient)(nil).ActivateAccessByLink), varargs...)
}

// AddCollaborator mocks base method.
func (m *MockSharingClient) AddCollaborator(ctx context.Context, in *v11.AddCollaboratorRequest, opts ...grpc.CallOption) (*v11.CollaboratorResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddCollaborator", varargs...)
	ret0, _ := ret[0].(*v11.CollaboratorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCollaborator indicates an expected call of AddCollaborator.
func (mr *MockSharingClientMockRecorder) AddCollaborator(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCollaborator", reflect.TypeOf((*MockSharingClient)(nil).AddCollaborator), varargs...)
}

// CheckNoteAccess mocks base method.
func (m *MockSharingClient) CheckNoteAccess(ctx context.Context, in *v11.CheckNoteAccessRequest, opts ...grpc.CallOption) (*v11.NoteAccessResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CheckNoteAccess", varargs...)
	ret0, _ := ret[0].(*v11.NoteAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckNoteAccess indicates an expected call of CheckNoteAccess.
func (mr *MockSharingClientMockRecorder) CheckNoteAccess(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNoteAccess", reflect.TypeOf((*MockSharingClient)(nil).CheckNoteAccess), varargs...)
}

// GetCollaborators mocks base method.
func (m *MockSharingClient) GetCollaborators(ctx context.Context, in *v11.GetCollaboratorsRequest, opts ...grpc.CallOption) (*v11.GetCollaboratorsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCollaborators", varargs...)
	ret0, _ := ret[0].(*v11.GetCollaboratorsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollaborators indicates an expected call of GetCollaborators.
func (mr *MockSharingClientMockRecorder) GetCollaborators(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollaborators", reflect.TypeOf((*MockSharingClient)(nil).GetCollaborators), varargs...)
}

// GetPublicAccess mocks base method.
func (m *MockSharingClient) GetPublicAccess(ctx context.Context, in *v11.GetPublicAccessRequest, opts ...grpc.CallOption) (*v11.PublicAccessResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPublicAccess", varargs...)
	ret0, _ := ret[0].(*v11.PublicAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicAccess indicates an expected call of GetPublicAccess.
func (mr *MockSharingClientMockRecorder) GetPublicAccess(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicAccess", reflect.TypeOf((*MockSharingClient)(nil).GetPublicAccess), varargs...)
}

// GetSharingSettings mocks base method.
func (m *MockSharingClient) GetSharingSettings(ctx context.Context, in *v11.GetSharingSettingsRequest, opts ...grpc.CallOption) (*v11.SharingSettingsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSharingSettings", varargs...)
	ret0, _ := ret[0].(*v11.SharingSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSharingSettings indicates an expected call of GetSharingSettings.
func (mr *MockSharingClientMockRecorder) GetSharingSettings(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharingSettings", reflect.TypeOf((*MockSharingClient)(nil).GetSharingSettings), varargs...)
}

// RemoveCollaborator mocks base method.
func (m *MockSharingClient) RemoveCollaborator(ctx context.Context, in *v11.RemoveCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveCollaborator", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveCollaborator indicates an expected call of RemoveCollaborator.
func (mr *MockSharingClientMockRecorder) RemoveCollaborator(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCollaborator", reflect.TypeOf((*MockSharingClient)(nil).RemoveCollaborator), varargs...)
}

// SetPublicAccess mocks base method.
func (m *MockSharingClient) SetPublicAccess(ctx context.Context, in *v11.SetPublicAccessRequest, opts ...grpc.CallOption) (*v11.PublicAccessResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetPublicAccess", varargs...)
	ret0, _ := ret[0].(*v11.PublicAccessResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPublicAccess indicates an expected call of SetPublicAccess.
func (mr *MockSharingClientMockRecorder) SetPublicAccess(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPublicAccess", reflect.TypeOf((*MockSharingClient)(nil).SetPublicAccess), varargs...)
}

// UpdateCollaboratorRole mocks base method.
func (m *MockSharingClient) UpdateCollaboratorRole(ctx context.Context, in *v11.UpdateCollaboratorRoleRequest, opts ...grpc.CallOption) (*v11.CollaboratorResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateCollaboratorRole", varargs...)
	ret0, _ := ret[0].(*v11.CollaboratorResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCollaboratorRole indicates an expected call of UpdateCollaboratorRole.
func (mr *MockSharingClientMockRecorder) UpdateCollaboratorRole(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCollaboratorRole", reflect.TypeOf((*MockSharingClient)(nil).UpdateCollaboratorRole), varargs...)
}
