// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	models "backend/notes_service/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNotesRepository is a mock of NotesRepository interface.
type MockNotesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotesRepositoryMockRecorder
}

// MockNotesRepositoryMockRecorder is the mock recorder for MockNotesRepository.
type MockNotesRepositoryMockRecorder struct {
	mock *MockNotesRepository
}

// NewMockNotesRepository creates a new mock instance.
func NewMockNotesRepository(ctrl *gomock.Controller) *MockNotesRepository {
	mock := &MockNotesRepository{ctrl: ctrl}
	mock.recorder = &MockNotesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotesRepository) EXPECT() *MockNotesRepositoryMockRecorder {
	return m.recorder
}

// AddFavorite mocks base method.
func (m *MockNotesRepository) AddFavorite(ctx context.Context, userID, noteID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFavorite", ctx, userID, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFavorite indicates an expected call of AddFavorite.
func (mr *MockNotesRepositoryMockRecorder) AddFavorite(ctx, userID, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFavorite", reflect.TypeOf((*MockNotesRepository)(nil).AddFavorite), ctx, userID, noteID)
}

// CreateNote mocks base method.
func (m *MockNotesRepository) CreateNote(ctx context.Context, userID uint64, parentNoteID *uint64) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNote", ctx, userID, parentNoteID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNote indicates an expected call of CreateNote.
func (mr *MockNotesRepositoryMockRecorder) CreateNote(ctx, userID, parentNoteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNote", reflect.TypeOf((*MockNotesRepository)(nil).CreateNote), ctx, userID, parentNoteID)
}

// DeleteNote mocks base method.
func (m *MockNotesRepository) DeleteNote(ctx context.Context, noteID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNote", ctx, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNote indicates an expected call of DeleteNote.
func (mr *MockNotesRepositoryMockRecorder) DeleteNote(ctx, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNote", reflect.TypeOf((*MockNotesRepository)(nil).DeleteNote), ctx, noteID)
}

// GetNoteById mocks base method.
func (m *MockNotesRepository) GetNoteById(ctx context.Context, noteID, userID uint64) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteById", ctx, noteID, userID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteById indicates an expected call of GetNoteById.
func (mr *MockNotesRepositoryMockRecorder) GetNoteById(ctx, noteID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteById", reflect.TypeOf((*MockNotesRepository)(nil).GetNoteById), ctx, noteID, userID)
}

// GetNoteByShareUUID mocks base method.
func (m *MockNotesRepository) GetNoteByShareUUID(ctx context.Context, shareUUID string) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNoteByShareUUID", ctx, shareUUID)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNoteByShareUUID indicates an expected call of GetNoteByShareUUID.
func (mr *MockNotesRepositoryMockRecorder) GetNoteByShareUUID(ctx, shareUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNoteByShareUUID", reflect.TypeOf((*MockNotesRepository)(nil).GetNoteByShareUUID), ctx, shareUUID)
}

// GetNotes mocks base method.
func (m *MockNotesRepository) GetNotes(ctx context.Context, userID uint64) ([]models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotes", ctx, userID)
	ret0, _ := ret[0].([]models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotes indicates an expected call of GetNotes.
func (mr *MockNotesRepositoryMockRecorder) GetNotes(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotes", reflect.TypeOf((*MockNotesRepository)(nil).GetNotes), ctx, userID)
}

// RemoveFavorite mocks base method.
func (m *MockNotesRepository) RemoveFavorite(ctx context.Context, userID, noteID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFavorite", ctx, userID, noteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFavorite indicates an expected call of RemoveFavorite.
func (mr *MockNotesRepositoryMockRecorder) RemoveFavorite(ctx, userID, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFavorite", reflect.TypeOf((*MockNotesRepository)(nil).RemoveFavorite), ctx, userID, noteID)
}

// SearchNotes mocks base method.
func (m *MockNotesRepository) SearchNotes(ctx context.Context, userID uint64, query string) (*models.SearchNotesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchNotes", ctx, userID, query)
	ret0, _ := ret[0].(*models.SearchNotesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchNotes indicates an expected call of SearchNotes.
func (mr *MockNotesRepositoryMockRecorder) SearchNotes(ctx, userID, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchNotes", reflect.TypeOf((*MockNotesRepository)(nil).SearchNotes), ctx, userID, query)
}

// SetHeader mocks base method.
func (m *MockNotesRepository) SetHeader(ctx context.Context, noteID, headerFileID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", ctx, noteID, headerFileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockNotesRepositoryMockRecorder) SetHeader(ctx, noteID, headerFileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockNotesRepository)(nil).SetHeader), ctx, noteID, headerFileID)
}

// SetIcon mocks base method.
func (m *MockNotesRepository) SetIcon(ctx context.Context, noteID, iconFileID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIcon", ctx, noteID, iconFileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetIcon indicates an expected call of SetIcon.
func (mr *MockNotesRepositoryMockRecorder) SetIcon(ctx, noteID, iconFileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIcon", reflect.TypeOf((*MockNotesRepository)(nil).SetIcon), ctx, noteID, iconFileID)
}

// UpdateNote mocks base method.
func (m *MockNotesRepository) UpdateNote(ctx context.Context, noteID uint64, title *string, isArchived *bool) (*models.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNote", ctx, noteID, title, isArchived)
	ret0, _ := ret[0].(*models.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateNote indicates an expected call of UpdateNote.
func (mr *MockNotesRepositoryMockRecorder) UpdateNote(ctx, noteID, title, isArchived interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNote", reflect.TypeOf((*MockNotesRepository)(nil).UpdateNote), ctx, noteID, title, isArchived)
}

// MockSharingRepository is a mock of SharingRepository interface.
type MockSharingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSharingRepositoryMockRecorder
}

// MockSharingRepositoryMockRecorder is the mock recorder for MockSharingRepository.
type MockSharingRepositoryMockRecorder struct {
	mock *MockSharingRepository
}

// NewMockSharingRepository creates a new mock instance.
func NewMockSharingRepository(ctrl *gomock.Controller) *MockSharingRepository {
	mock := &MockSharingRepository{ctrl: ctrl}
	mock.recorder = &MockSharingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSharingRepository) EXPECT() *MockSharingRepositoryMockRecorder {
	return m.recorder
}

// CheckNoteAccess mocks base method.
func (m *MockSharingRepository) CheckNoteAccess(ctx context.Context, noteID, userID uint64) (*models.NoteAccessInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckNoteAccess", ctx, noteID, userID)
	ret0, _ := ret[0].(*models.NoteAccessInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckNoteAccess indicates an expected call of CheckNoteAccess.
func (mr *MockSharingRepositoryMockRecorder) CheckNoteAccess(ctx, noteID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNoteAccess", reflect.TypeOf((*MockSharingRepository)(nil).CheckNoteAccess), ctx, noteID, userID)
}
