auth:
  cors:
    allowed_origins:
      - "http://localhost:8030"
      - "http://127.0.0.1:8030"
      - "http://89.208.210.115:8030"

  cookie:
    session_duration: 30

  csrf:
    secret_key: "your-32-byte-secret-key-here-change-in-prod" # 32 символа для AES-256
    token_ttl_minutes: 30