// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: notes_service/proto/block/v1/block.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NoteId    uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Type      string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Position  float64                `protobuf:"fixed64,4,opt,name=position,proto3" json:"position,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*Block_TextContent
	//	*Block_CodeContent
	//	*Block_AttachmentContent
	Content       isBlock_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Block) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *Block) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Block) GetPosition() float64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Block) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Block) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Block) GetContent() isBlock_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Block) GetTextContent() *TextContent {
	if x != nil {
		if x, ok := x.Content.(*Block_TextContent); ok {
			return x.TextContent
		}
	}
	return nil
}

func (x *Block) GetCodeContent() *CodeContent {
	if x != nil {
		if x, ok := x.Content.(*Block_CodeContent); ok {
			return x.CodeContent
		}
	}
	return nil
}

func (x *Block) GetAttachmentContent() *AttachmentContent {
	if x != nil {
		if x, ok := x.Content.(*Block_AttachmentContent); ok {
			return x.AttachmentContent
		}
	}
	return nil
}

type isBlock_Content interface {
	isBlock_Content()
}

type Block_TextContent struct {
	TextContent *TextContent `protobuf:"bytes,7,opt,name=text_content,json=textContent,proto3,oneof"`
}

type Block_CodeContent struct {
	CodeContent *CodeContent `protobuf:"bytes,8,opt,name=code_content,json=codeContent,proto3,oneof"`
}

type Block_AttachmentContent struct {
	AttachmentContent *AttachmentContent `protobuf:"bytes,9,opt,name=attachment_content,json=attachmentContent,proto3,oneof"`
}

func (*Block_TextContent) isBlock_Content() {}

func (*Block_CodeContent) isBlock_Content() {}

func (*Block_AttachmentContent) isBlock_Content() {}

type TextContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Formats       []*BlockTextFormat     `protobuf:"bytes,2,rep,name=formats,proto3" json:"formats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextContent) Reset() {
	*x = TextContent{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextContent) ProtoMessage() {}

func (x *TextContent) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextContent.ProtoReflect.Descriptor instead.
func (*TextContent) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{1}
}

func (x *TextContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextContent) GetFormats() []*BlockTextFormat {
	if x != nil {
		return x.Formats
	}
	return nil
}

type CodeContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeContent) Reset() {
	*x = CodeContent{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeContent) ProtoMessage() {}

func (x *CodeContent) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeContent.ProtoReflect.Descriptor instead.
func (*CodeContent) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{2}
}

func (x *CodeContent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CodeContent) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type AttachmentContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Caption       *string                `protobuf:"bytes,2,opt,name=caption,proto3,oneof" json:"caption,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes     int32                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Width         *int32                 `protobuf:"varint,5,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height        *int32                 `protobuf:"varint,6,opt,name=height,proto3,oneof" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachmentContent) Reset() {
	*x = AttachmentContent{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachmentContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachmentContent) ProtoMessage() {}

func (x *AttachmentContent) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachmentContent.ProtoReflect.Descriptor instead.
func (*AttachmentContent) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{3}
}

func (x *AttachmentContent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AttachmentContent) GetCaption() string {
	if x != nil && x.Caption != nil {
		return *x.Caption
	}
	return ""
}

func (x *AttachmentContent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AttachmentContent) GetSizeBytes() int32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *AttachmentContent) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *AttachmentContent) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

type BlockTextFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartOffset   int32                  `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset     int32                  `protobuf:"varint,3,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	Bold          bool                   `protobuf:"varint,4,opt,name=bold,proto3" json:"bold,omitempty"`
	Italic        bool                   `protobuf:"varint,5,opt,name=italic,proto3" json:"italic,omitempty"`
	Underline     bool                   `protobuf:"varint,6,opt,name=underline,proto3" json:"underline,omitempty"`
	Strikethrough bool                   `protobuf:"varint,7,opt,name=strikethrough,proto3" json:"strikethrough,omitempty"`
	Link          *string                `protobuf:"bytes,8,opt,name=link,proto3,oneof" json:"link,omitempty"`
	Font          string                 `protobuf:"bytes,9,opt,name=font,proto3" json:"font,omitempty"`
	Size          int32                  `protobuf:"varint,10,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockTextFormat) Reset() {
	*x = BlockTextFormat{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockTextFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockTextFormat) ProtoMessage() {}

func (x *BlockTextFormat) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockTextFormat.ProtoReflect.Descriptor instead.
func (*BlockTextFormat) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{4}
}

func (x *BlockTextFormat) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlockTextFormat) GetStartOffset() int32 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *BlockTextFormat) GetEndOffset() int32 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *BlockTextFormat) GetBold() bool {
	if x != nil {
		return x.Bold
	}
	return false
}

func (x *BlockTextFormat) GetItalic() bool {
	if x != nil {
		return x.Italic
	}
	return false
}

func (x *BlockTextFormat) GetUnderline() bool {
	if x != nil {
		return x.Underline
	}
	return false
}

func (x *BlockTextFormat) GetStrikethrough() bool {
	if x != nil {
		return x.Strikethrough
	}
	return false
}

func (x *BlockTextFormat) GetLink() string {
	if x != nil && x.Link != nil {
		return *x.Link
	}
	return ""
}

func (x *BlockTextFormat) GetFont() string {
	if x != nil {
		return x.Font
	}
	return ""
}

func (x *BlockTextFormat) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetBlocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksRequest) Reset() {
	*x = GetBlocksRequest{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksRequest) ProtoMessage() {}

func (x *GetBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksRequest.ProtoReflect.Descriptor instead.
func (*GetBlocksRequest) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{5}
}

func (x *GetBlocksRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetBlocksRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

type GetBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*Block               `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlocksResponse) Reset() {
	*x = GetBlocksResponse{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlocksResponse) ProtoMessage() {}

func (x *GetBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlocksResponse.ProtoReflect.Descriptor instead.
func (*GetBlocksResponse) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{6}
}

func (x *GetBlocksResponse) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type GetBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockId       uint64                 `protobuf:"varint,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockRequest) Reset() {
	*x = GetBlockRequest{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockRequest) ProtoMessage() {}

func (x *GetBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockRequest.ProtoReflect.Descriptor instead.
func (*GetBlockRequest) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{7}
}

func (x *GetBlockRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetBlockRequest) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

type CreateTextBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	BeforeBlockId *uint64                `protobuf:"varint,3,opt,name=before_block_id,json=beforeBlockId,proto3,oneof" json:"before_block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTextBlockRequest) Reset() {
	*x = CreateTextBlockRequest{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTextBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTextBlockRequest) ProtoMessage() {}

func (x *CreateTextBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTextBlockRequest.ProtoReflect.Descriptor instead.
func (*CreateTextBlockRequest) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTextBlockRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTextBlockRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *CreateTextBlockRequest) GetBeforeBlockId() uint64 {
	if x != nil && x.BeforeBlockId != nil {
		return *x.BeforeBlockId
	}
	return 0
}

type CreateCodeBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	BeforeBlockId *uint64                `protobuf:"varint,3,opt,name=before_block_id,json=beforeBlockId,proto3,oneof" json:"before_block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCodeBlockRequest) Reset() {
	*x = CreateCodeBlockRequest{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCodeBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCodeBlockRequest) ProtoMessage() {}

func (x *CreateCodeBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCodeBlockRequest.ProtoReflect.Descriptor instead.
func (*CreateCodeBlockRequest) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCodeBlockRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCodeBlockRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *CreateCodeBlockRequest) GetBeforeBlockId() uint64 {
	if x != nil && x.BeforeBlockId != nil {
		return *x.BeforeBlockId
	}
	return 0
}

type CreateAttachmentBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteId        uint64                 `protobuf:"varint,2,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	BeforeBlockId *uint64                `protobuf:"varint,3,opt,name=before_block_id,json=beforeBlockId,proto3,oneof" json:"before_block_id,omitempty"`
	FileId        uint64                 `protobuf:"varint,4,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAttachmentBlockRequest) Reset() {
	*x = CreateAttachmentBlockRequest{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAttachmentBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAttachmentBlockRequest) ProtoMessage() {}

func (x *CreateAttachmentBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAttachmentBlockRequest.ProtoReflect.Descriptor instead.
func (*CreateAttachmentBlockRequest) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{10}
}

func (x *CreateAttachmentBlockRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAttachmentBlockRequest) GetNoteId() uint64 {
	if x != nil {
		return x.NoteId
	}
	return 0
}

func (x *CreateAttachmentBlockRequest) GetBeforeBlockId() uint64 {
	if x != nil && x.BeforeBlockId != nil {
		return *x.BeforeBlockId
	}
	return 0
}

func (x *CreateAttachmentBlockRequest) GetFileId() uint64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

type UpdateBlockRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	UserId  uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockId uint64                 `protobuf:"varint,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Type    string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*UpdateBlockRequest_TextContent
	//	*UpdateBlockRequest_CodeContent
	Content       isUpdateBlockRequest_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlockRequest) Reset() {
	*x = UpdateBlockRequest{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlockRequest) ProtoMessage() {}

func (x *UpdateBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlockRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlockRequest) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateBlockRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateBlockRequest) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *UpdateBlockRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateBlockRequest) GetContent() isUpdateBlockRequest_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpdateBlockRequest) GetTextContent() *TextContent {
	if x != nil {
		if x, ok := x.Content.(*UpdateBlockRequest_TextContent); ok {
			return x.TextContent
		}
	}
	return nil
}

func (x *UpdateBlockRequest) GetCodeContent() *CodeContent {
	if x != nil {
		if x, ok := x.Content.(*UpdateBlockRequest_CodeContent); ok {
			return x.CodeContent
		}
	}
	return nil
}

type isUpdateBlockRequest_Content interface {
	isUpdateBlockRequest_Content()
}

type UpdateBlockRequest_TextContent struct {
	TextContent *TextContent `protobuf:"bytes,4,opt,name=text_content,json=textContent,proto3,oneof"`
}

type UpdateBlockRequest_CodeContent struct {
	CodeContent *CodeContent `protobuf:"bytes,5,opt,name=code_content,json=codeContent,proto3,oneof"`
}

func (*UpdateBlockRequest_TextContent) isUpdateBlockRequest_Content() {}

func (*UpdateBlockRequest_CodeContent) isUpdateBlockRequest_Content() {}

type DeleteBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockId       uint64                 `protobuf:"varint,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlockRequest) Reset() {
	*x = DeleteBlockRequest{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlockRequest) ProtoMessage() {}

func (x *DeleteBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlockRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlockRequest) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteBlockRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteBlockRequest) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

type UpdateBlockPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockId       uint64                 `protobuf:"varint,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	BeforeBlockId *uint64                `protobuf:"varint,3,opt,name=before_block_id,json=beforeBlockId,proto3,oneof" json:"before_block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlockPositionRequest) Reset() {
	*x = UpdateBlockPositionRequest{}
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlockPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlockPositionRequest) ProtoMessage() {}

func (x *UpdateBlockPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notes_service_proto_block_v1_block_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlockPositionRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlockPositionRequest) Descriptor() ([]byte, []int) {
	return file_notes_service_proto_block_v1_block_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateBlockPositionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateBlockPositionRequest) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *UpdateBlockPositionRequest) GetBeforeBlockId() uint64 {
	if x != nil && x.BeforeBlockId != nil {
		return *x.BeforeBlockId
	}
	return 0
}

var File_notes_service_proto_block_v1_block_proto protoreflect.FileDescriptor

const file_notes_service_proto_block_v1_block_proto_rawDesc = "" +
	"\n" +
	"(notes_service/proto/block/v1/block.proto\x12\x05block\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9e\x03\n" +
	"\x05Block\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x01R\bposition\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\ftext_content\x18\a \x01(\v2\x12.block.TextContentH\x00R\vtextContent\x127\n" +
	"\fcode_content\x18\b \x01(\v2\x12.block.CodeContentH\x00R\vcodeContent\x12I\n" +
	"\x12attachment_content\x18\t \x01(\v2\x18.block.AttachmentContentH\x00R\x11attachmentContentB\t\n" +
	"\acontent\"S\n" +
	"\vTextContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x120\n" +
	"\aformats\x18\x02 \x03(\v2\x16.block.BlockTextFormatR\aformats\"=\n" +
	"\vCodeContent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\"\xd9\x01\n" +
	"\x11AttachmentContent\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\acaption\x18\x02 \x01(\tH\x00R\acaption\x88\x01\x01\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x05R\tsizeBytes\x12\x19\n" +
	"\x05width\x18\x05 \x01(\x05H\x01R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\x06 \x01(\x05H\x02R\x06height\x88\x01\x01B\n" +
	"\n" +
	"\b_captionB\b\n" +
	"\x06_widthB\t\n" +
	"\a_height\"\x9d\x02\n" +
	"\x0fBlockTextFormat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12!\n" +
	"\fstart_offset\x18\x02 \x01(\x05R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x03 \x01(\x05R\tendOffset\x12\x12\n" +
	"\x04bold\x18\x04 \x01(\bR\x04bold\x12\x16\n" +
	"\x06italic\x18\x05 \x01(\bR\x06italic\x12\x1c\n" +
	"\tunderline\x18\x06 \x01(\bR\tunderline\x12$\n" +
	"\rstrikethrough\x18\a \x01(\bR\rstrikethrough\x12\x17\n" +
	"\x04link\x18\b \x01(\tH\x00R\x04link\x88\x01\x01\x12\x12\n" +
	"\x04font\x18\t \x01(\tR\x04font\x12\x12\n" +
	"\x04size\x18\n" +
	" \x01(\x05R\x04sizeB\a\n" +
	"\x05_link\"D\n" +
	"\x10GetBlocksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\"9\n" +
	"\x11GetBlocksResponse\x12$\n" +
	"\x06blocks\x18\x01 \x03(\v2\f.block.BlockR\x06blocks\"E\n" +
	"\x0fGetBlockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\x04R\ablockId\"\x8b\x01\n" +
	"\x16CreateTextBlockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\x12+\n" +
	"\x0fbefore_block_id\x18\x03 \x01(\x04H\x00R\rbeforeBlockId\x88\x01\x01B\x12\n" +
	"\x10_before_block_id\"\x8b\x01\n" +
	"\x16CreateCodeBlockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\x12+\n" +
	"\x0fbefore_block_id\x18\x03 \x01(\x04H\x00R\rbeforeBlockId\x88\x01\x01B\x12\n" +
	"\x10_before_block_id\"\xaa\x01\n" +
	"\x1cCreateAttachmentBlockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x17\n" +
	"\anote_id\x18\x02 \x01(\x04R\x06noteId\x12+\n" +
	"\x0fbefore_block_id\x18\x03 \x01(\x04H\x00R\rbeforeBlockId\x88\x01\x01\x12\x17\n" +
	"\afile_id\x18\x04 \x01(\x04R\x06fileIdB\x12\n" +
	"\x10_before_block_id\"\xd9\x01\n" +
	"\x12UpdateBlockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\x04R\ablockId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x127\n" +
	"\ftext_content\x18\x04 \x01(\v2\x12.block.TextContentH\x00R\vtextContent\x127\n" +
	"\fcode_content\x18\x05 \x01(\v2\x12.block.CodeContentH\x00R\vcodeContentB\t\n" +
	"\acontent\"H\n" +
	"\x12DeleteBlockRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\x04R\ablockId\"\x91\x01\n" +
	"\x1aUpdateBlockPositionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\x04R\ablockId\x12+\n" +
	"\x0fbefore_block_id\x18\x03 \x01(\x04H\x00R\rbeforeBlockId\x88\x01\x01B\x12\n" +
	"\x10_before_block_id2\x8e\x04\n" +
	"\fBlockService\x12>\n" +
	"\tGetBlocks\x12\x17.block.GetBlocksRequest\x1a\x18.block.GetBlocksResponse\x120\n" +
	"\bGetBlock\x12\x16.block.GetBlockRequest\x1a\f.block.Block\x12>\n" +
	"\x0fCreateTextBlock\x12\x1d.block.CreateTextBlockRequest\x1a\f.block.Block\x12>\n" +
	"\x0fCreateCodeBlock\x12\x1d.block.CreateCodeBlockRequest\x1a\f.block.Block\x12J\n" +
	"\x15CreateAttachmentBlock\x12#.block.CreateAttachmentBlockRequest\x1a\f.block.Block\x126\n" +
	"\vUpdateBlock\x12\x19.block.UpdateBlockRequest\x1a\f.block.Block\x12@\n" +
	"\vDeleteBlock\x12\x19.block.DeleteBlockRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x13UpdateBlockPosition\x12!.block.UpdateBlockPositionRequest\x1a\f.block.BlockB$Z\"backend/notes_service/pkg/block/v1b\x06proto3"

var (
	file_notes_service_proto_block_v1_block_proto_rawDescOnce sync.Once
	file_notes_service_proto_block_v1_block_proto_rawDescData []byte
)

func file_notes_service_proto_block_v1_block_proto_rawDescGZIP() []byte {
	file_notes_service_proto_block_v1_block_proto_rawDescOnce.Do(func() {
		file_notes_service_proto_block_v1_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notes_service_proto_block_v1_block_proto_rawDesc), len(file_notes_service_proto_block_v1_block_proto_rawDesc)))
	})
	return file_notes_service_proto_block_v1_block_proto_rawDescData
}

var file_notes_service_proto_block_v1_block_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_notes_service_proto_block_v1_block_proto_goTypes = []any{
	(*Block)(nil),                        // 0: block.Block
	(*TextContent)(nil),                  // 1: block.TextContent
	(*CodeContent)(nil),                  // 2: block.CodeContent
	(*AttachmentContent)(nil),            // 3: block.AttachmentContent
	(*BlockTextFormat)(nil),              // 4: block.BlockTextFormat
	(*GetBlocksRequest)(nil),             // 5: block.GetBlocksRequest
	(*GetBlocksResponse)(nil),            // 6: block.GetBlocksResponse
	(*GetBlockRequest)(nil),              // 7: block.GetBlockRequest
	(*CreateTextBlockRequest)(nil),       // 8: block.CreateTextBlockRequest
	(*CreateCodeBlockRequest)(nil),       // 9: block.CreateCodeBlockRequest
	(*CreateAttachmentBlockRequest)(nil), // 10: block.CreateAttachmentBlockRequest
	(*UpdateBlockRequest)(nil),           // 11: block.UpdateBlockRequest
	(*DeleteBlockRequest)(nil),           // 12: block.DeleteBlockRequest
	(*UpdateBlockPositionRequest)(nil),   // 13: block.UpdateBlockPositionRequest
	(*timestamppb.Timestamp)(nil),        // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 15: google.protobuf.Empty
}
var file_notes_service_proto_block_v1_block_proto_depIdxs = []int32{
	14, // 0: block.Block.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: block.Block.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: block.Block.text_content:type_name -> block.TextContent
	2,  // 3: block.Block.code_content:type_name -> block.CodeContent
	3,  // 4: block.Block.attachment_content:type_name -> block.AttachmentContent
	4,  // 5: block.TextContent.formats:type_name -> block.BlockTextFormat
	0,  // 6: block.GetBlocksResponse.blocks:type_name -> block.Block
	1,  // 7: block.UpdateBlockRequest.text_content:type_name -> block.TextContent
	2,  // 8: block.UpdateBlockRequest.code_content:type_name -> block.CodeContent
	5,  // 9: block.BlockService.GetBlocks:input_type -> block.GetBlocksRequest
	7,  // 10: block.BlockService.GetBlock:input_type -> block.GetBlockRequest
	8,  // 11: block.BlockService.CreateTextBlock:input_type -> block.CreateTextBlockRequest
	9,  // 12: block.BlockService.CreateCodeBlock:input_type -> block.CreateCodeBlockRequest
	10, // 13: block.BlockService.CreateAttachmentBlock:input_type -> block.CreateAttachmentBlockRequest
	11, // 14: block.BlockService.UpdateBlock:input_type -> block.UpdateBlockRequest
	12, // 15: block.BlockService.DeleteBlock:input_type -> block.DeleteBlockRequest
	13, // 16: block.BlockService.UpdateBlockPosition:input_type -> block.UpdateBlockPositionRequest
	6,  // 17: block.BlockService.GetBlocks:output_type -> block.GetBlocksResponse
	0,  // 18: block.BlockService.GetBlock:output_type -> block.Block
	0,  // 19: block.BlockService.CreateTextBlock:output_type -> block.Block
	0,  // 20: block.BlockService.CreateCodeBlock:output_type -> block.Block
	0,  // 21: block.BlockService.CreateAttachmentBlock:output_type -> block.Block
	0,  // 22: block.BlockService.UpdateBlock:output_type -> block.Block
	15, // 23: block.BlockService.DeleteBlock:output_type -> google.protobuf.Empty
	0,  // 24: block.BlockService.UpdateBlockPosition:output_type -> block.Block
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_notes_service_proto_block_v1_block_proto_init() }
func file_notes_service_proto_block_v1_block_proto_init() {
	if File_notes_service_proto_block_v1_block_proto != nil {
		return
	}
	file_notes_service_proto_block_v1_block_proto_msgTypes[0].OneofWrappers = []any{
		(*Block_TextContent)(nil),
		(*Block_CodeContent)(nil),
		(*Block_AttachmentContent)(nil),
	}
	file_notes_service_proto_block_v1_block_proto_msgTypes[3].OneofWrappers = []any{}
	file_notes_service_proto_block_v1_block_proto_msgTypes[4].OneofWrappers = []any{}
	file_notes_service_proto_block_v1_block_proto_msgTypes[8].OneofWrappers = []any{}
	file_notes_service_proto_block_v1_block_proto_msgTypes[9].OneofWrappers = []any{}
	file_notes_service_proto_block_v1_block_proto_msgTypes[10].OneofWrappers = []any{}
	file_notes_service_proto_block_v1_block_proto_msgTypes[11].OneofWrappers = []any{
		(*UpdateBlockRequest_TextContent)(nil),
		(*UpdateBlockRequest_CodeContent)(nil),
	}
	file_notes_service_proto_block_v1_block_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notes_service_proto_block_v1_block_proto_rawDesc), len(file_notes_service_proto_block_v1_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notes_service_proto_block_v1_block_proto_goTypes,
		DependencyIndexes: file_notes_service_proto_block_v1_block_proto_depIdxs,
		MessageInfos:      file_notes_service_proto_block_v1_block_proto_msgTypes,
	}.Build()
	File_notes_service_proto_block_v1_block_proto = out.File
	file_notes_service_proto_block_v1_block_proto_goTypes = nil
	file_notes_service_proto_block_v1_block_proto_depIdxs = nil
}
