// Code generated by MockGen. DO NOT EDIT.
// Source: gateway_service/internal/middleware/middleware.go
//
// Generated by this command:
//
//	mockgen -source=gateway_service/internal/middleware/middleware.go -destination=gateway_service/internal/middleware/mock/mock_session.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSessionValidator is a mock of SessionValidator interface.
type MockSessionValidator struct {
	ctrl     *gomock.Controller
	recorder *MockSessionValidatorMockRecorder
	isgomock struct{}
}

// MockSessionValidatorMockRecorder is the mock recorder for MockSessionValidator.
type MockSessionValidatorMockRecorder struct {
	mock *MockSessionValidator
}

// NewMockSessionValidator creates a new mock instance.
func NewMockSessionValidator(ctrl *gomock.Controller) *MockSessionValidator {
	mock := &MockSessionValidator{ctrl: ctrl}
	mock.recorder = &MockSessionValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionValidator) EXPECT() *MockSessionValidatorMockRecorder {
	return m.recorder
}

// ValidateSession mocks base method.
func (m *MockSessionValidator) ValidateSession(ctx context.Context, sessionID string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", ctx, sessionID)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockSessionValidatorMockRecorder) ValidateSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockSessionValidator)(nil).ValidateSession), ctx, sessionID)
}
