#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE user_db;
    CREATE DATABASE notes_db;
    CREATE DATABASE files_db;
    
    GRANT ALL PRIVILEGES ON DATABASE user_db TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE notes_db TO "$POSTGRES_USER";
    GRANT ALL PRIVILEGES ON DATABASE files_db TO "$POSTGRES_USER";
EOSQL