// Code generated by MockGen. DO NOT EDIT.
// Source: delivery.go

// Package mock is a generated GoMock package.
package mock

import (
	models "backend/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockBlocksUsecase is a mock of BlocksUsecase interface.
type MockBlocksUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockBlocksUsecaseMockRecorder
}

// MockBlocksUsecaseMockRecorder is the mock recorder for MockBlocksUsecase.
type MockBlocksUsecaseMockRecorder struct {
	mock *MockBlocksUsecase
}

// NewMockBlocksUsecase creates a new mock instance.
func NewMockBlocksUsecase(ctrl *gomock.Controller) *MockBlocksUsecase {
	mock := &MockBlocksUsecase{ctrl: ctrl}
	mock.recorder = &MockBlocksUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlocksUsecase) EXPECT() *MockBlocksUsecaseMockRecorder {
	return m.recorder
}

// CreateAttachmentBlock mocks base method.
func (m *MockBlocksUsecase) CreateAttachmentBlock(ctx context.Context, userID, noteID uint64, beforeBlockID *uint64, fileID uint64) (*models.BlockWithContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttachmentBlock", ctx, userID, noteID, beforeBlockID, fileID)
	ret0, _ := ret[0].(*models.BlockWithContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttachmentBlock indicates an expected call of CreateAttachmentBlock.
func (mr *MockBlocksUsecaseMockRecorder) CreateAttachmentBlock(ctx, userID, noteID, beforeBlockID, fileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttachmentBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).CreateAttachmentBlock), ctx, userID, noteID, beforeBlockID, fileID)
}

// CreateCodeBlock mocks base method.
func (m *MockBlocksUsecase) CreateCodeBlock(ctx context.Context, userID, noteID uint64, beforeBlockID *uint64) (*models.BlockWithContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCodeBlock", ctx, userID, noteID, beforeBlockID)
	ret0, _ := ret[0].(*models.BlockWithContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCodeBlock indicates an expected call of CreateCodeBlock.
func (mr *MockBlocksUsecaseMockRecorder) CreateCodeBlock(ctx, userID, noteID, beforeBlockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCodeBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).CreateCodeBlock), ctx, userID, noteID, beforeBlockID)
}

// CreateTextBlock mocks base method.
func (m *MockBlocksUsecase) CreateTextBlock(ctx context.Context, userID, noteID uint64, beforeBlockID *uint64) (*models.BlockWithContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTextBlock", ctx, userID, noteID, beforeBlockID)
	ret0, _ := ret[0].(*models.BlockWithContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTextBlock indicates an expected call of CreateTextBlock.
func (mr *MockBlocksUsecaseMockRecorder) CreateTextBlock(ctx, userID, noteID, beforeBlockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTextBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).CreateTextBlock), ctx, userID, noteID, beforeBlockID)
}

// DeleteBlock mocks base method.
func (m *MockBlocksUsecase) DeleteBlock(ctx context.Context, userID, blockID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlock", ctx, userID, blockID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlock indicates an expected call of DeleteBlock.
func (mr *MockBlocksUsecaseMockRecorder) DeleteBlock(ctx, userID, blockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).DeleteBlock), ctx, userID, blockID)
}

// GetBlock mocks base method.
func (m *MockBlocksUsecase) GetBlock(ctx context.Context, userID, blockID uint64) (*models.BlockWithContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", ctx, userID, blockID)
	ret0, _ := ret[0].(*models.BlockWithContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockBlocksUsecaseMockRecorder) GetBlock(ctx, userID, blockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).GetBlock), ctx, userID, blockID)
}

// GetBlocks mocks base method.
func (m *MockBlocksUsecase) GetBlocks(ctx context.Context, userID, noteID uint64) ([]models.BlockWithContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlocks", ctx, userID, noteID)
	ret0, _ := ret[0].([]models.BlockWithContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlocks indicates an expected call of GetBlocks.
func (mr *MockBlocksUsecaseMockRecorder) GetBlocks(ctx, userID, noteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlocks", reflect.TypeOf((*MockBlocksUsecase)(nil).GetBlocks), ctx, userID, noteID)
}

// UpdateBlock mocks base method.
func (m *MockBlocksUsecase) UpdateBlock(ctx context.Context, userID, blockID uint64, text, language, codeText *string, formats []models.BlockTextFormat) (*models.BlockWithContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlock", ctx, userID, blockID, text, language, codeText, formats)
	ret0, _ := ret[0].(*models.BlockWithContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlock indicates an expected call of UpdateBlock.
func (mr *MockBlocksUsecaseMockRecorder) UpdateBlock(ctx, userID, blockID, text, language, codeText, formats interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlock", reflect.TypeOf((*MockBlocksUsecase)(nil).UpdateBlock), ctx, userID, blockID, text, language, codeText, formats)
}

// UpdateBlockPosition mocks base method.
func (m *MockBlocksUsecase) UpdateBlockPosition(ctx context.Context, userID, blockID uint64, afterBlockID *uint64) (*models.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockPosition", ctx, userID, blockID, afterBlockID)
	ret0, _ := ret[0].(*models.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBlockPosition indicates an expected call of UpdateBlockPosition.
func (mr *MockBlocksUsecaseMockRecorder) UpdateBlockPosition(ctx, userID, blockID, afterBlockID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockPosition", reflect.TypeOf((*MockBlocksUsecase)(nil).UpdateBlockPosition), ctx, userID, blockID, afterBlockID)
}
