// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: auth_service/proto/auth/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetUserIDBySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIDBySessionRequest) Reset() {
	*x = GetUserIDBySessionRequest{}
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIDBySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIDBySessionRequest) ProtoMessage() {}

func (x *GetUserIDBySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIDBySessionRequest.ProtoReflect.Descriptor instead.
func (*GetUserIDBySessionRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserIDBySessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetUserIDBySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIDBySessionResponse) Reset() {
	*x = GetUserIDBySessionResponse{}
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIDBySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIDBySessionResponse) ProtoMessage() {}

func (x *GetUserIDBySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIDBySessionResponse.ProtoReflect.Descriptor instead.
func (*GetUserIDBySessionResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserIDBySessionResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *GetUserIDBySessionResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCSRFTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCSRFTokenRequest) Reset() {
	*x = GetCSRFTokenRequest{}
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCSRFTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCSRFTokenRequest) ProtoMessage() {}

func (x *GetCSRFTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCSRFTokenRequest.ProtoReflect.Descriptor instead.
func (*GetCSRFTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GetCSRFTokenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetCSRFTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCSRFTokenResponse) Reset() {
	*x = GetCSRFTokenResponse{}
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCSRFTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCSRFTokenResponse) ProtoMessage() {}

func (x *GetCSRFTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_service_proto_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCSRFTokenResponse.ProtoReflect.Descriptor instead.
func (*GetCSRFTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_service_proto_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *GetCSRFTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_auth_service_proto_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_service_proto_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"%auth_service/proto/auth/v1/auth.proto\x12\x04auth\x1a\x1bgoogle/protobuf/empty.proto\"/\n" +
	"\x14CreateSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\".\n" +
	"\rLogoutRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\":\n" +
	"\x19GetUserIDBySessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"P\n" +
	"\x1aGetUserIDBySessionResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"4\n" +
	"\x13GetCSRFTokenRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\",\n" +
	"\x14GetCSRFTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xaf\x02\n" +
	"\x04Auth\x12J\n" +
	"\rCreateSession\x12\x1a.auth.CreateSessionRequest\x1a\x1b.auth.CreateSessionResponse\"\x00\x127\n" +
	"\x06Logout\x12\x13.auth.LogoutRequest\x1a\x16.google.protobuf.Empty\"\x00\x12Y\n" +
	"\x12GetUserIDBySession\x12\x1f.auth.GetUserIDBySessionRequest\x1a .auth.GetUserIDBySessionResponse\"\x00\x12G\n" +
	"\fGetCSRFToken\x12\x19.auth.GetCSRFTokenRequest\x1a\x1a.auth.GetCSRFTokenResponse\"\x00B\"Z backend/auth_service/pkg/auth/v1b\x06proto3"

var (
	file_auth_service_proto_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_service_proto_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_service_proto_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_service_proto_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_service_proto_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_service_proto_auth_v1_auth_proto_rawDesc), len(file_auth_service_proto_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_service_proto_auth_v1_auth_proto_rawDescData
}

var file_auth_service_proto_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_service_proto_auth_v1_auth_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),       // 0: auth.CreateSessionRequest
	(*CreateSessionResponse)(nil),      // 1: auth.CreateSessionResponse
	(*LogoutRequest)(nil),              // 2: auth.LogoutRequest
	(*GetUserIDBySessionRequest)(nil),  // 3: auth.GetUserIDBySessionRequest
	(*GetUserIDBySessionResponse)(nil), // 4: auth.GetUserIDBySessionResponse
	(*GetCSRFTokenRequest)(nil),        // 5: auth.GetCSRFTokenRequest
	(*GetCSRFTokenResponse)(nil),       // 6: auth.GetCSRFTokenResponse
	(*emptypb.Empty)(nil),              // 7: google.protobuf.Empty
}
var file_auth_service_proto_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.Auth.CreateSession:input_type -> auth.CreateSessionRequest
	2, // 1: auth.Auth.Logout:input_type -> auth.LogoutRequest
	3, // 2: auth.Auth.GetUserIDBySession:input_type -> auth.GetUserIDBySessionRequest
	5, // 3: auth.Auth.GetCSRFToken:input_type -> auth.GetCSRFTokenRequest
	1, // 4: auth.Auth.CreateSession:output_type -> auth.CreateSessionResponse
	7, // 5: auth.Auth.Logout:output_type -> google.protobuf.Empty
	4, // 6: auth.Auth.GetUserIDBySession:output_type -> auth.GetUserIDBySessionResponse
	6, // 7: auth.Auth.GetCSRFToken:output_type -> auth.GetCSRFTokenResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_service_proto_auth_v1_auth_proto_init() }
func file_auth_service_proto_auth_v1_auth_proto_init() {
	if File_auth_service_proto_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_service_proto_auth_v1_auth_proto_rawDesc), len(file_auth_service_proto_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_service_proto_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_service_proto_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_service_proto_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_service_proto_auth_v1_auth_proto = out.File
	file_auth_service_proto_auth_v1_auth_proto_goTypes = nil
	file_auth_service_proto_auth_v1_auth_proto_depIdxs = nil
}
